### ISSUE TITLE
Landing Cuidate A Tiempo. Org

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#1]
Fede, te estoy enviando por WeTransfer una landing para armar para FUCA, la fundación contra el cancer. Esta ya va en versión responsive muy simple.

Por favor confirmame si tenés ya los datos del hosting de cuidateatiempo.org

abrazo

**Comment by LeandroBraier** [comment]
Ya se envió todo por WeTransfer. Confirmame si lo recibiste porfa:

Acá van los datos de acceso al hosting:

Usuario: cuidatea
Contraseña: jrU254lNr4
Si no solicitaste la registración del dominio y utilizaras un dominio ya registrado, o planeas registrarlo por tu cuenta, resulta indispensable que lo delegues a nuestros DNS:

ns1.duplika.com / 199.102.230.88
ns2.duplika.com / 50.28.56.141
Si no sabes como delegar tu dominio, consulta éstos pasos o contactanos. Conocé como acceder a tu plan mientras el dominio no esté delegado.

Panel de control

Tu panel de control cPanel es desde donde podras administrar tu sitio.

cPanel
cPanel (acceso temporal)
Subir archivos

Todos los archivos que quieras subir a tu sitio deberan ser ubicados en la carpeta public_html. Conocé como subir arhivos desde tu navegador o bien accedé via FTP para mayor comodidad.

FTP host: ftp.cuidateatiempo.org
FTP (acceso temporal): 72.52.188.252

**Comment by FAAREIA** [comment]
Hola Lea, ahi la vi! No esta muy bien hecha, seguramente haga algunos cambios, por ejemplo los campos tienen muy poca altura para clickearlos con el dedo.

**Comment by LeandroBraier** [comment]
Dale, cambialo tranquilo. El diseño lo hizo la diseñadora y yo lo adapté a
Mobile porque, si bien le pedí que no usara tipografías tan chicas y demás,
no lo llegó a cambiar lo suficiente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-10 14:18 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hola Lea, te paso los avances hasta hoy.

Lo que falta:
- El formulario no funciona
- Meter los fondos
- Terminar el encabezado
- Terminar lo de desarrollado por benteveo.

http://www.benteveo.tv/_cat/

**Comment by LeandroBraier** [comment]
Funcionalmente vamos bien. Si bien con cambios, Intentemos acercarnos todo
lo posible a la estética y a las fuentes del diseño ese. Sino va a quedar
muy básico y de colores chillones.

No sé si lo ves así, pero te mando captura de lo que veo mal en el
encabezado.

abrazo grande y buen finde!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-10 19:38 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hola Lea, ahora cuando lo veas terminado va a acercarse más al original. Con respecto a las fuentes, no son tipografías web por lo que les meto las más similar, si es que la hay. Tampoco trabajen en CMYK porque los colores van en RGB.

**Comment by LeandroBraier** [comment]
Es cierto eso. Es un error que me pasa siempre ultimamente con FUCA. No se va a repetir. Gracias!

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_cat/

El formulario aún no envía

**Comment by FAAREIA** [comment]
Ahi esta lo del form lea

**Comment by FAAREIA** [comment]
Ahi subi la versión responsiva + fixes.
Un detalle, no esta preparado para IE8 el sitio. Los logos e iconos son vectores.

**Comment by LeandroBraier** [comment]
Excelente Fede! Lo paso para aprobación así ya lo subimos al server correcto. Prepará todo para eso mientras tanto.

abrazo

**Comment by LeandroBraier** [comment]
Che, perdón, está ok, pero falta el pop up cuando cargo el formulario. Subimelo y lo paso para aprobación

abrazo

**Comment by FAAREIA** [comment]
Si, falta eso y un fix para IE9.
Repregunto: ¿estas seguro que lo prepare para IE8? Me gustaría empezar a dejarlo de lado, ya en unos 3 meses caduca por completo practicamente

**Comment by LeandroBraier** [comment]
IE8 dejalo de lado por ahora. Si alguien chilla lo adaptamos.

**Comment by FAAREIA** [comment]
Excelente Lea. Ahi esta subida la última versión, dale F5.
¿A que email va el formulario?

**Comment by LeandroBraier** [comment]
Eso lo veo con MK en ticket aparte. Por ahora mandalo a mi mail de gmail
también.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahora va a: leandrobraier@gmail.com

**Comment by LeandroBraier** [comment]
Ya está lista la landing responsive Fede?

**Comment by FAAREIA** [comment]
Asi es, ya esta lista

**Comment by LeandroBraier** [comment]
Ok, porfa entonces pasala a su dominio definitivo en cuidateatiempo.org

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Mirá que el link de la nota no existe aun, estas seguro?

**Comment by LeandroBraier** [comment]
Te referís a la trivia? Tenemos que crear ese pop up pero me parece mejor
ya trabajar sobre el hosting real, total no lo vamos a estar comunicando
hasta el domingo.

ahora te paso ticket aparte por esa trivia y por los mails automáticos.
Pero quiero cerrar este ticket de la landing. Ya enviamos al cliente pero
no hubo feedback por ahora. A Eze y Marce S les gustó.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Listo, ya esta subido al sitio oficial

**Comment by LeandroBraier** [comment]
Perfecto. Pongamosle el logo de FUCA redondido como FAVICON en alta calidad
(igual que el de Benteveo) y empezá a armar la versión web, menos compacta,
ya que en pantallas grandes queda demasiado a amontonado todo al centro.
Para responsive está perfecta.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, frenemos la adaptación web que te pedí para la landing. Por ahora queda así responsive, yo te aviso cualquier otro cambio. Quiero que te puedas enfocar en la trivia y los mailings y empecemos a hacer tests mañana a primera hora por las dudas.

Me quedo con este ticket yo por si hay cambios del cliente.

abrazo

**Comment by FAAREIA** [comment]
La adaptación ya esta hecha. Mañana hacemos lo de la trivia y los mailings

**Comment by LeandroBraier** [comment]
Ok. Pero intentemos tener los mailings entonces, así podemos hacer las
pruebas. La trivia puede ser a la tarde.

Respecto de la landing, ¿entonces hoy ya la dejás subida con esa
adaptación? Lo que veo es que el mensaje pop up que aparece diciendo "¡Ya
programaste tu mamografía!" no se lee bien. Creo que se leería mejor si
cuando das enviar, todo alrededor del form se ve blureado o en otro color
y, al hacer clic, se desblurea. Es posible?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-16 16:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya esta subida la landing, en última versión que tiene el ajuste para
desktop, que es una reorganización de los elementos. El blur se puede
meter, pero es pesado y no todos los navegadores lo soportan. Podemos tapar
el form y que quede el mensaje arriba, centrado.

**Comment by LeandroBraier** [comment]
Ok. está subida al dominio oficial? Porque no la veo.

Me parece OK tapar elformulario con el mensaje si lleva menos recursos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-16 17:24 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://cuidateatiempo.org/
F5

**Comment by LeandroBraier** [comment]
Si, lo veo, pero no noto mucho la diferencia la verdad. SImplemente
agrandaste todo, no? De todas formas no quiero que inviertas más tiempo en
eso. Así está OK.

Avancemos con los mails y luego con la trivia.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-16 17:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Se reordenó, no agrandé ningun tamaño. ^^
El form lo puse a la derecha como si fuese una publicidad, asi se ve 2
veces...

**Comment by LeandroBraier** [comment]
Fede, al ingresar fechas en los campos de fecha, el calendario que se despliega debajo del campo no se ve bien. Te adjunto captura. 

![captura de pantalla 2014-10-17 a la s 16 23 57](https://cloud.githubusercontent.com/assets/6719872/4684475/f69d4794-5630-11e4-849a-42aff08f3995.png)

**Comment by LeandroBraier** [comment]
Fede, mejoró, pero sigue con problemas. Mirá:

![captura de pantalla 2014-10-17 a la s 17 26 58](https://cloud.githubusercontent.com/assets/6719872/4685671/d6a793ac-563c-11e4-934f-be888e6a03e5.png)

**Comment by LeandroBraier** [comment]
Ahora sí está perfecto. Apenas puedas, te pediría que en la versión Web hagas que la frase "Cuidate a tiempo" de arriba de todo se vea más grande, llegando al margen izquierdo del diseño.

**Comment by LeandroBraier** [comment]
Fede, dos pequeños agregandos.
1. En la página de Modificación de Datos faltaría un botón de "Desuscribirme" 
2. Cuando alguien nunca se hizo una mamografía, debería tildar un casillero que dijera: "Nunca me hice una mamografía". En ese caso de acuerdo a la edad le tendría que llegar directamente el mail nº 4, de recordatorio efectivo o los otros mails de bienvenida diciéndole que aún no está en edad de hacerla.

Confirmame si recibiste esto porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya esta eso. No entendí lo de la frase llegando al margen izquierdo.

**Comment by LeandroBraier** [comment]
No es tan importante ni urgente. Es que la frase "Cuidate a tiempo" en
verde de arriba esté más grande. Siento el título de la página queda muy
perdida. Te decía que la agrandes para que se alinea con el margen
izquierdo de la página, a la misma altura que empieza la foto, por ejemplo.

Lo del botón de "desuscribirme" hay que avisarle a MK que lo active, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Recién probé programarme la mamografía y en el mensaje de respuesta que se
superpone sobre el form después de Enviar se sigue viendo el casillero de
"Nunca me hice una mamografía." Eso habría que cambiarlo, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-17 20:29 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA cómo andan? Necesito 2 detalles sencillos acá:

1) Que le agreguen en el formulario el campo para llenar el Teléfono de la persona.

2) Acceder a la base de inscriptos hasta el momento. Me la mandarían por favor?

abrazo

**Comment by mkreyness** [comment]
no me funciona el user/pass que figura en el thread (de 2014) no se si cambio o se migro el hosting o que. Hace años que no entro ahi.

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Cómo hacemos entonces? Le escribimos a Duplika?

**Comment by mkreyness** [comment]
capaz @FAAREIA los tenga ? En los ultimos cambios yo no intervine.

**Comment by LeandroBraier** [comment]
Yo me acuerdo que el año pasado algún cambio hicimos ahí.

**Comment by FAAREIA** [comment]
cuidatea
anJVMjU0bE5yNA==

**Comment by FAAREIA** [comment]
Ahi agregué el campo al archivo `indexT.html`. No lo veo actualizado aún. Tarda en regenerase o hay que regenerarlo?

**Comment by mkreyness** [comment]
no hay nada que regenere paginas aca, lo tiene que usar on the fly.
Pero con ese user/pass no puedo entrar por SSH. Eso debe ser para FTP pero no para SSH.
Ya di mil vueltas con los certificados y no me lo toma. A la tarde pruebo desde la oficina, igual ahora desaparezco por varias horas.

**Comment by FAAREIA** [comment]
Claro, era del FTP.
Ahi agregué el campo al index.html también, que es el que se ve al entrar al dominio.

**Comment by LeandroBraier** [comment]
Perfecto Fede! Muchas gracias! Quedó perfecto. Recién lo testeé.

@mkreyness solo me faltaría el listado de suscriptos con sus datos para mandarle al cliente.

abrazo

**Comment by mkreyness** [comment]
ya pude entrar.
Igual no hacia falta, encontre que hicimos un CMS para esto en su momento:

http://www.cuidateatiempo.org/cgi-bin/cuidate.pl

user: admin
pass: benteveo

**Comment by mkreyness** [comment]
ahi tenes una consulta de registrados donde podes filtrar con distintos criterios (o ninguno).

**Comment by LeandroBraier** [comment]
Excelente MK!! Eso necesitaba!! gracias! No te jodo más por esto.

abrazo
