### ISSUE TITLE
Error 505

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#10]
Buen día MK! Los errores 505 que hay en el CMS ocurren también al hacer clic en los links de los mails. Habría que resolverlo

**Comment by mkreyness** [comment]
Que raro, con los mails nunca me pasó. Tenes el link con que te pasó ?
El problema siempre es que no tengo acceso a los logs de errores como 
para saber de que se queja.
Trataré de que lo miren los de Duplika.

**Comment by LeandroBraier** [comment]
Sí, era este el link:

<goog_690774128>
http://www.cuidateatiempo.org/cgi-bin/editarfuca.pl?id=35&dig=c51fcae1e245b2c5556a23ac04b2895f492aca10

De todas formas ahora lo volví a probar y no me pasó de nuevo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-24 13:39 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Eso es lo choto, que no se puede reproducir, ni mirar que es lo que le 
molesta.
Voy a tratar de forzarlo por el lado del CMS que es mas frecuente como 
para decirles a los de Duplika que hora buscar en el log.

**Comment by LeandroBraier** [comment]
Esto ya está resuelto, no?

**Comment by mkreyness** [comment]
```
Mira, estuve hablando mucho con la gente de Duplika y no hubo una
razon exacta por la cual se arreglara, pero despues de un reinicio
que tuvieron en el servidor (supongo que involuntario) se arregló
solo.
Para mi habia algo cacheado viejo que se libero al reiniciarse.
A mi no me volvio a dar.

El 30/10/2014 a las 11:52,
  LeandroBraier escribió:


  Esto ya está resuelto, no?
  —
    Reply to this email directly or view
      it on GitHub.
  {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/FUCA/issues/10#issuecomment-61104720">"https://github.com/LeandroBraier/FUCA/issues/10#issuecomment-61104720"</a>,"name":"View Issue"}}
```

**Comment by LeandroBraier** [comment]
Genial! A mi tampoco. Cierro el ticket entonces. abrazo
