### ISSUE TITLE
Newsletter Cuidate a Tiempo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#11]
Fede, necesito que me armes un newsletter en HTML en base a un posteo que te subí a Benteveo Maquetador.

Lo tenés en PSD. También te subí una adaptación en formato de Banner por si te sirve también. Podrá estar para hoy a la tarde?

abrazo

**Comment by LeandroBraier** [comment]
Claramente habría que agregarle un botón con un link que lleve a la landing, no? Y el link debería tener un /?mail=1 o algo así

abrazo

**Comment by FAAREIA** [comment]
Lo puse todo como imagen, sino las tipografías van a cambiar y el fondo tampoco lo puedo respetar.
http://www.cuidateatiempo.org/mailing/programa-mamografia.html

**Comment by LeandroBraier** [comment]
Fede, necesito que lo adaptes más a formato newsletter y responsive. Podés usar el fondo de los mails automáticos del programador de FUCA.

abrazo

**Comment by FAAREIA** [comment]
Ok, le adapto a newsletter entonces. Pero como siempre las tipografías y los fondos van a cambiar, al menos un poco.
Los mailing no pueden ser responsivos, no hay form de detectar el ancho disponible en el dispositivo

**Comment by LeandroBraier** [comment]
ok, hagamoslo lo más angosto posible (igual no tanto como esta imagen que
me mandaste) y adaptando las tipografías y fondos como vos decís.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-30 14:24 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
lo que te mandé es el ancho máximo de cualquier mailing, más grande no se puede

**Comment by LeandroBraier** [comment]
Te referís al ancho de la página o del fondo rosa de la imagen? Yo me
refiero a lo segundo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Claro, la imagen esta en 640px, es el ancho máximo de los mailing. Más se puede pero seguro a alguno se le rompe la estructura.

**Comment by FAAREIA** [comment]
Ahi va la nueva versión:
http://www.cuidateatiempo.org/mailing/programa-mamografia/programa-mamografia.html

**Comment by mkreyness** [comment]
Me perdi, yo tengo que hacer algo con esto ?

**Comment by LeandroBraier** [comment]
Ahora si está listo el Newsletter. Gracias Fede!

Ahora que está listo sí me podés ayudar, pero no de la forma que pensás. Te explico:

Vamos a enviar este newsletter a una base de 500 mil mujeres de capital que compramos. Vamos a contractar a un servicio para esto, en particular se llama Ineva. Voy a comenzar enviandole gratis a 500 usuarios para ver si la página es buena y la base sirve. Si eso funciona, le paso las 500 mil a Ineva. La cuestión es que voy a necesitar tu ayuda para pasarle el html a Ineva.

Mañana lo pruebo y te digo.

abrazo a los dos

**Comment by FAAREIA** [comment]
Joya, cualquier cosa avisa

**Comment by LeandroBraier** [comment]
Dale, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
MK, hay posibilidad de que la prueba de los primeros 500 mails la hagas vos, como hacés con los mails de Benteveo?

Es solo para probar si es buena la base de datos. Si es buena, ahí contratamos a Embleu o a una empresa más importante. Estos de Ineva no les funciona la página de ellos y no me respondieron en 4 días.

**Comment by mkreyness** [comment]
```
Pero no tengo como medir rebotes ni nada, si los mando (como deberia
ser) desde el mailserver de cuidateatiempo, no tengo acceso
practicamente a nada. 
Como vas a saber si la base es buena o no ?

El 03/11/2014 a las 10:21,
  LeandroBraier escribió:


  MK, hay posibilidad de que la prueba de los primeros 500 mails
    la hagas vos, como hacés con los mails de Benteveo?
  Es solo para probar si es buena la base de datos. Si es buena,
    ahí contratamos a Embleu o a una empresa más importante. Estos
    de Ineva no les funciona la página de ellos y no me respondieron
    en 4 días.
  —
    Reply to this email directly or view
      it on GitHub.
  {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61475943">"https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61475943"</a>,"name":"View Issue"}}
```

**Comment by LeandroBraier** [comment]
Lástima que no podamos medir rebotes, pero sí podemos medir  los clics
reales que generen los mails. Esos sí los podemos medir por Analytics, y ni
hablar si incrementan la cantidad de suscriptos al programador de
mamografías. El tema es que es caro el servicio si no te da pruebas. Voy a
seguir investigando pero deicme si es posible que al menos midamos los
rebotes de alguna forma.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-03 10:26 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No tengo acceso a los rebotes a nivel servidor, eso cae en un
archivo general del hosting, mezclado con los rebotes de todos los
demas que usen el mismo servidor.
SI es que el servidor se molesta en mandar un aviso del rebote (que
no es lo mismo que el rebote) al sender, tendriamos que definir un
sender que sea accesible.
En este momento es fuca@cuidateatiempo.org, que esta redireccionada
a leandrobraier@gmail.com.
Te llego alguna vez algun rebote o respuesta de alguien por
"cuidate" ahi ?

El 03/11/2014 a las 10:34,
  LeandroBraier escribió:

Lástima que no podamos medir rebotes, pero sí podemos
  medir los clics

  reales que generen los mails. Esos sí los podemos medir por
  Analytics, y ni

  hablar si incrementan la cantidad de suscriptos al programador de

  mamografías. El tema es que es caro el servicio si no te da
  pruebas. Voy a

  seguir investigando pero deicme si es posible que al menos midamos
  los

  rebotes de alguna forma.




  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-11-03 10:26 GMT-03:00 mkreyness
  <notifications@github.com>:


  >

  >

  >

  >

  >

  > Pero no tengo como medir rebotes ni nada, si los mando (como
  deberia

  > ser) desde el mailserver de cuidateatiempo, no tengo acceso

  > practicamente a nada.

  > Como vas a saber si la base es buena o no ?

  >

  > El 03/11/2014 a las 10:21,

  > LeandroBraier escribió:

  >

  >

  > MK, hay posibilidad de que la prueba de los primeros 500
  mails

  > la hagas vos, como hacés con los mails de Benteveo?

  > Es solo para probar si es buena la base de datos. Si es
  buena,

  > ahí contratamos a Embleu o a una empresa más importante.
  Estos

  > de Ineva no les funciona la página de ellos y no me
  respondieron

  > en 4 días.

  > —

  > Reply to this email directly or view

  > it on GitHub.

  > {"@context":<a class="moz-txt-link-rfc2396E"
  href="http://schema.org">"

  >
  http://schema.org"</a>,"@type":"EmailMessage","description":"View
  this

  > Issue on GitHub","action":{"@type":"ViewAction","url":<a

  > class="moz-txt-link-rfc2396E" href="

  >
```

https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61475943">"
      >
https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61475943"</a>,"name":"View
      > Issue"}}

```
  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61476399.
      >
      —
        Reply to this email directly or view
          it on GitHub.
      {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61477369">"https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61477369"</a>,"name":"View Issue"}}

**Comment by LeandroBraier** [comment]
Nop. Ni uno.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-03 10:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Confirmado Marce. Hagamos los 500 de esta manera mañana a las 9.30 am.

Confirmame vos si te llegó el excel y el txt con los 500 mails. Va sin nombre, solo mail. El Subject y el from ya los tenés.

abrazo

**Comment by LeandroBraier** [comment]
Marce, confirmado. Haceles el filtro y las usamos para enviar a los mails que se pueda. Te envié la base entera por WeTransfer. Confirmame si la recibiste.

abrazo

**Comment by mkreyness** [comment]
Recibido, bajando.

**Comment by mkreyness** [comment]
La limpie con estos criterios, y siguen quedando muchos, con mucha 
basura, por ejemplo hay toneladas que se llaman info@, por lo tanto no 
creo que sean "mujeres", mas bien son empresas.
Por otro lado, por ejemplo hay muchisimos "alfredo", "gustavo", etc. que 
me sospecho que son hombres.
Yo te lo limpio enseguida eso, ya que esta todo ordenado alfabetico y es 
super evidente.
En definitiva igual van a quedar cientos de miles, tomo de ahi 500 al 
azar y los mando ?

**Comment by LeandroBraier** [comment]
Dale, hagamos así.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-03 17:35 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No encuentro que me hayas pasado el Asunto: con que enviarlo, seria
lo que dice la foto ? "¿Hace cuánto que no te hacés una mamografía?"

El 03/11/2014 a las 17:40,
  LeandroBraier escribió:

Dale, hagamos así.


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-11-03 17:35 GMT-03:00 mkreyness
  <notifications@github.com>:


  > La limpie con estos criterios, y siguen quedando muchos, con
  mucha

  > basura, por ejemplo hay toneladas que se llaman info@, por lo
  tanto no

  > creo que sean "mujeres", mas bien son empresas.

  > Por otro lado, por ejemplo hay muchisimos "alfredo",
  "gustavo", etc. que

  > me sospecho que son hombres.

  > Yo te lo limpio enseguida eso, ya que esta todo ordenado
  alfabetico y es

  > super evidente.

  > En definitiva igual van a quedar cientos de miles, tomo de
  ahi 500 al

  > azar y los mando ?

  >

  >

  > On 03/11/2014 04:58 p.m., Marcelo Kreyness wrote:

  > > Recibido, bajando.

  > >

  > > On 03/11/2014 04:55 p.m., LeandroBraier wrote:

  > >>

  > >> Marce, confirmado. Haceles el filtro y las usamos
  para enviar a los

  > >> mails que se pueda. Te envié la base entera por
  WeTransfer.

  > >> Confirmame si la recibiste.

  > >>

  > >> abrazo

  > >>

  > >> —

  > >> Reply to this email directly or view it on GitHub

  > >>
```

<https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61537813
      > >.

```
  > >>

  > >

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61543971.
      >
      —
        Reply to this email directly or view
          it on GitHub.
      {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61544685">"https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61544685"</a>,"name":"View Issue"}}

**Comment by LeandroBraier** [comment]
"Programá tu mamografía de una vez para toda la vida" es el subject. Lo enviarías mañana?

**Comment by mkreyness** [comment]
```
Lo envie ayer a los 500 de prueba, con subject igual a lo que decia
la foto.
Queres que mande a otros 500 con este subject ?

El 05/11/2014 a las 20:24,
  LeandroBraier escribió:


  "Programá tu mamografía de una vez para toda la vida" es el
    subject. Lo enviarías mañana?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Dale, hagamos eso. Porque la verdad: impacto nulo. 1 subscripta nueva en la
landing nomás. Mandale a 500 o a 1000 si podés y si no funca ya desistimos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-05 20:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
ok, lo largo a la mañana entonces, tene en cuenta que va a tardar un
par de horas porque hay delays random de entre 1 y 10 segundos entre
mail y mail. 

El 05/11/2014 a las 21:04,
  LeandroBraier escribió:

Dale, hagamos eso. Porque la verdad: impacto nulo. 1
  subscripta nueva en la

  landing nomás. Mandale a 500 o a 1000 si podés y si no funca ya
  desistimos.


  abrazo


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-11-05 20:46 GMT-03:00 mkreyness
  <notifications@github.com>:


  >

  >

  >

  >

  >

  > Lo envie ayer a los 500 de prueba, con subject igual a lo que
  decia

  > la foto.

  > Queres que mande a otros 500 con este subject ?

  >

  > El 05/11/2014 a las 20:24,

  > LeandroBraier escribió:

  >

  >

  > "Programá tu mamografía de una vez para toda la vida" es el

  > subject. Lo enviarías mañana?

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61903490.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
No hay problema, es el último intento ya.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-05 21:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Mira que lo recontradepure de porquerias infernales, trate de que
todos fueran o nombres de mujer o apellidos cuyo nombre fuera una
inicial y por si acaso supongo que el 50% de eso son mujeres.

No sabes las truchadas que habia, miles y miles de:

postmaster@
hostmaster@
support@
info@
y sobre todo unos hdp "Jose Marti" y "Fernando Casas" o algo asi que
(no se si son los mismos que venden la base) que estan tipo asi:

j.m@arnet.com.ar
jo.m@arnet.com.ar
jos.m@arnet.com.ar
jose.m@arnet.com.ar
jose.ma@arnet.com.ar
jose.mar@arnet.com.ar
jose.mart@arnet.com.ar
jose.marti@arnet.com.ar
f.c@arnet.com.ar
fe.c@arnet.com.ar
fer.c@arnet.com.ar
fern.c@arnet.com.ar
ferna.c@arnet.com.ar
...
fernando.casas@arnet.com.ar

y asi repetido por todos los proveedores .com.ar que se te pueda
ocurrir.


El 05/11/2014 a las 21:22,
  LeandroBraier escribió:

No hay problema, es el último intento ya.


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-11-05 21:12 GMT-03:00 mkreyness
  <notifications@github.com>:


  >

  >

  >

  >

  >

  > ok, lo largo a la mañana entonces, tene en cuenta que va a
  tardar un

  > par de horas porque hay delays random de entre 1 y 10
  segundos entre

  > mail y mail.

  >

  > El 05/11/2014 a las 21:04,

  > LeandroBraier escribió:

  >

  > Dale, hagamos eso. Porque la verdad: impacto nulo. 1

  > subscripta nueva en la

  >

  > landing nomás. Mandale a 500 o a 1000 si podés y si no funca
  ya

  > desistimos.

  >

  >

  > abrazo

  >

  >

  > Leandro Braier

  >

  > Producción Audiovisual & Social Media

  >

  > Benteveo Producciones <http://benteveo.tv>

  >

  > Móvil 1158717399

  >

  >

  > 2014-11-05 20:46 GMT-03:00 mkreyness

  > <notifications@github.com>:

  >

  >

  > >

  >

  > >

  >

  > >

  >

  > >

  >

  > >

  >

  > > Lo envie ayer a los 500 de prueba, con subject igual a
  lo que

  > decia

  >

  > > la foto.

  >

  > > Queres que mande a otros 500 con este subject ?

  >

  > >

  >

  > > El 05/11/2014 a las 20:24,

  >

  > > LeandroBraier escribió:

  >

  > >

  >

  > >

  >

  > > "Programá tu mamografía de una vez para toda la vida" es
  el

  >

  > > subject. Lo enviarías mañana?

  >

  > > —

  >

  > > Reply to this email directly or view

  >

  > > it on GitHub.

  >

  > >

  >

  > > —

  >

  > > Reply to this email directly or view it on GitHub

  >

  > >

  >
```

https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61903490.
      >

```
  > >

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/FUCA/issues/11#issuecomment-61906237.
      >
      —
        Reply to this email directly or view
          it on GitHub.
