### ISSUE TITLE
Página de Tweets FUCA #LaFotoDelAño

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#13]
@braulio-evangelisti , necesito que me hagas una pagina en benteveo.tv/FUCA/ que tenga este listado de tweets y que cada uno tenga un botón de "Copy".

https://docs.google.com/spreadsheets/d/14Q3p6wvD_nDCtbXK7IcJDNtmK_-71SVqP5Ql8G3_tMU/edit#gid=0

¿Para qué la necesito? Tengo que enviar muchos mensajes de twitter en pocos minutos y, para evitar escribirlos uno por uno con el celular, necesito ir copiandolos de una página.

Porfa confirmame si podés tenerlo para el lunes.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea fijate ahi

http://www.benteveo.tv/fuca/

Le puse 3 botones a cada uno
1) Copia el texto al portapapeles.
2) Abre dialogo desde el navegador con el texto redactado para luego compartirlo (si hay una cuenta de twitter logeada, sino te pide iniciar sesion)
3) Intenta abrir la aplicacion de twitter con el texto redactado para luego compartirlo.

Pegale una testeada a ver si te funciona, desconozco desde que telefono, con que sistema operativo y navegador vas a realizar el procedimiento.

Abrazo

**Comment by LeandroBraier** [comment]
Está buenisimo Brau!!

Lo chequeo con el equipo de redes a ver si l ven OK

abrazo
