### ISSUE TITLE
Acceso a CPANEL FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#15]
@braulio-evangelisti cómo estás?

Te estoy pasando por mail el acceso al CPanel de la web de FUCA. Lo que necesito es que me digas si podrías sumar un POP UP de inicio a la web actual que está online solo con este acceso o si necesitás algo más.

abrazo

**Comment by braulio-evangelisti** [comment]
No estoy teniendo acceso al sitio Lea. Voy a ir probando cada tanto apenas pueda conectarme te aviso pero calculo que con esos datos ya tendria que poder descargar el sitio actual, agregarle el popup y resubir lo que se necesite.

**Comment by LeandroBraier** [comment]
Fijate que da como un error de seguridad pero te deja entrar. Entrá a las
opciones avanzadas de abajo y vas a poder entrar.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-26 13:12 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Si conozco el caso, tiene que ver con https según entiendo, pero no es por eso, puedo loguearme una vez al panel, pero cada vez que quiero acceder desde el FTP se cae el sitio o bloquea por un rato mi ip porque después de eso me aparece como caído (tanto el publico como el panel) por un tiempo hasta que agarra de nuevo. Nunca me paso algo similar. A lo mejor Marcelo tenga una idea?

**Comment by LeandroBraier** [comment]
Mk probarias vos a ver si te pasa lo mismo? Es raro.

**Comment by braulio-evangelisti** [comment]
Ahi agarro Lea, estoy bajando el sitio. Anda tirandome la data del popup, que va a tener de info, si aparece cuando carga el sitio, solo en la home o no, etc.

**Comment by LeandroBraier** [comment]
Excelente Brau! Pensalo igual que el subimos a Revear. Es una imagen de 800
x 600 ponele que aparece al cargar la home la primera vez.

**Comment by braulio-evangelisti** [comment]
Joya, bueno creo que ya tengo armada la estructura en local, si me pasas la imagen pruebo como queda y apenas me des el ok lo puedo subir

**Comment by braulio-evangelisti** [comment]
Tambien avisame si al hacerle click tiene que llevar a algun lado o solo funciona como imagen

**Comment by LeandroBraier** [comment]
Dale. En un ratito te paso ambas cosas. Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti te paso el pop up.

<img width="607" alt="pop up fuca" src="https://cloud.githubusercontent.com/assets/6719872/12598493/6625bea0-c469-11e5-8b94-e8d3b76bfe6b.png">

El link al que tiene que llevar es este:

http://fuca.org.ar/formulario.htm

Gracias Brau!

**Comment by braulio-evangelisti** [comment]
Listo ya esta andando, lo tuve que achicar un poco para que tenga en cuenta la altura de la ventana del navegador.

Abrazo

**Comment by LeandroBraier** [comment]
Genial, lo puedo ver en algún link? Así se lo muestro al cliente y me da el
OK para subirlo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
http://www.fuca.org.ar/_index.htm

**Comment by LeandroBraier** [comment]
Muchas gracias Brau!!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Está perfecto @braulio-evangelisti ! Aprobado por el cliente!

Lo podés subir ya?

**Comment by braulio-evangelisti** [comment]
Ya esta en producción Lea

**Comment by LeandroBraier** [comment]
Excelente Braulio!!! Gracias!!!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti necesito que le sumes Analytics a este sitio (el que está ahora online). Tenés el acceso ya.

Te paso el acceso al gmail para que le sumes el Analytics.

**Comment by braulio-evangelisti** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti !!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti Necesito que quitemos cuanto antes el pop up de la página porfa. Lo antes posible

abrazo

**Comment by braulio-evangelisti** [comment]
Hecho. Abrazo.

**Comment by LeandroBraier** [comment]
Mil gracias Brau!
