### ISSUE TITLE
Nuevo POP en Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#16]
@braulio-evangelisti cuando puedas subís este pop en la web?

![afiche_16](https://cloud.githubusercontent.com/assets/6719872/13538643/92250ae0-e22a-11e5-8a2a-b8e0bdcaeb5d.jpg)

Como hicimos la otra vez. Se que lo ideal es que el pop sea cuadrado, pero me lo pasaron así. FIjate si queda bien porfa

abrazo

**Comment by braulio-evangelisti** [comment]
hecho!

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! Lo único que te pido si le podés sacar el link al formulario de donación al Pop Up. Solo eso abrazo

**Comment by braulio-evangelisti** [comment]
Es lunes! jajaja se me paso. Ahi se lo saque.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! Obvio, todo bien. Maldito lunes.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA hoy necesitaría que sacaras porfa el POP UP que hay en la actual Web de FUCA en www.fuca.org.ar

Lo hacía Brau pero ya no está ; (

abrazo

**Comment by FAAREIA** [comment]
El FTP lo tenés por ahi? Tengo el de cuidate a tiempo nomás.

**Comment by LeandroBraier** [comment]
Si, obvio. Ahi te reenvié los datos que le envié a Braulio.

Confirmame si recibiste.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !
