### ISSUE TITLE
CMS Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#17]
@mkreyness y @FAAREIA los pongo en contacto.

@FAAREIA acaba de entregar completa y maquetada la web. Necesito poder modificar los contenidos por CMS: (slides, textos, links, novedades, todo lo que es lógico actualizar frecuentemente)

Avisenme si necesitan algo. Yo necesito saber para cuándo podría tener disponible este CMS.

abrazo

**Comment by mkreyness** [comment]
Donde lo miro para tomarme una idea del volumen ?
Por otro lado, el servidor en que esta FUCA se banca todo esto ? No era muy de minima ?

**Comment by LeandroBraier** [comment]
El servidor actual donde está la web de FUCA vieja y nosotros tenemos
acceso es el que deben revisar. Si hay que expandirlo me avisan y lo
expandimos.

**Comment by mkreyness** [comment]
la maquetacion esta ahi ? Seguro no esta en benteveo.tv ?
Lo que pido es que me pases un link para verla.

**Comment by LeandroBraier** [comment]
Esto que hizo Fede está en benteveo. Eso seguro.

Pero la web final debería estar en donde ahora está www.fuca.org.ar

Fede tiene el acceso. Te reenvio por mail.

**Comment by mkreyness** [comment]
Lo que digo es que el server de FUCA tiene solo 1Gb de disco, del cual ahora (sin casi nada) tiene ocupado 1/3.
Seguro que con el site + content esos 600Mb no son suficientes.

**Comment by LeandroBraier** [comment]
@FAAREIA definan uds. Si necesitan más me avisan y le pido al cliente.

**Comment by mkreyness** [comment]
@FAAREIA cuanto calculas que va a ocupar con el content real ? Hay algun estimado de volumen de contenido ? Igual para mi los 600mb disponibles no pueden ser suficientes para nada.

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness necesito que avancemos con esto. Cómo vienen?

**Comment by mkreyness** [comment]
@FAAREIA danos una señal de vida.
Hay que ampliar ese servidor seguro, pero lo que no se es a cuanto.
Y @LeandroBraier , repito mi pedido, me podes pasar un link a lo que este en benteveo de esto ?

**Comment by mkreyness** [comment]
SI no lo veo, no puedo hacer nada.

**Comment by LeandroBraier** [comment]
Aca va MK:

http://fuca3.benteveo.tv/index.php

**Comment by mkreyness** [comment]
la parte variable seria solamente la que se nota que tiene cosas "lorem ipsum", o donde se ven contenidos reales tambien habria que manejarlos por CMS ?

**Comment by FAAREIA** [comment]
Actualmente lo puse en el servidor de benteveo porque para probarlo necesito que sea un subdominio asi toma bien las rutas que empiezan con "/" y simulo un dominio real.
Por otra parte, 600MB pueden llegar a servir para ahora pero no a futuro.

Lo del CMS hay que verlo bien, pero las unicas maquetas hechas que lo necesitan es el home y eventos.
Más allá de eso aca tengo 29 pantallas diseñadas y actualmente hay 9 maquetadas. Además hay secciones que nunca se diseñaron porque faltaba definir el contenido.
Para mi lo mejor sería ver con cuantas pantallas terminamos el viernes y ahi empezar a hacer el CMS y el resto.

**Comment by LeandroBraier** [comment]
@mkreyness ya definimos con Fede. Te digo en qué secciones necesito tener CMS si o si:

. Eventos

. Prensa

. Novedades y cuales se despliegan en la Home

. Slideshow

. Definir qué nota de cada una de estas secciones se muestra en la home: Formación Médica, Centro de Investigaciones CIO, Biblioteca FUCA y Fuca en la Comunidad

Confirmanos si estamos OK para avanzar. 

abrazo

**Comment by mkreyness** [comment]
eventos/prensa/novedades no es todo mas o menos lo mismo ? Ya se que van separados, pero basicamente podriamos cargar todo como novedades y ponerles un dato de "Tipo" para que sepa en cual de las tres secciones se muestran ?

**Comment by LeandroBraier** [comment]
Ahora no me está andando la maqueta como para verlo y confirmarte. En principio no son lo mismo porque se despliega diferente tipo de info. Por ejemplo:

Eventos: Foto de un determinado formato (para que lo levanto la home) + título + texto

Prensa: Foto de otro formato + texto + link

Novedades: Foto más grande + titulo + texto

@FAAREIA confirmanos vos qué opinás de este tema y avisame cuando va a estar de vuelta visible la maqueta en la web. No sé por qué la bajaron porque yo ya se la mandé al cliente.

**Comment by mkreyness** [comment]
sera cosa de Duplika ? Yo no toque nada.

**Comment by FAAREIA** [comment]
## Faltantes
- Prensa -> Novedades @LeandroBraier (en proceso)
- Prevención -> Charlas en la comunidad @LeandroBraier (en proceso)
- Prevención -> Eventos @LeandroBraier (en proceso)
- Pedir modulo perl "Spreadsheet::WriteExcel" @mkreyness @LeandroBraier 
- Formulario de [Voluntarios](http://fuca3.fuca.org.ar/quienes-somos/voluntarios.php) @mkreyness

---

## ¿Cómo chequear los mensajes de un formulario?
- Agregar `?a=s` o `?a=e` en la url. `a` es de alert, `s` de success y `e` de error

---

## Detalles / Errores / etc
- Email del form de Voluntarios: fuca.colaboracion@gmail.com @mkreyness 
- El formulario de [Doná Hoy](http://fuca3.fuca.org.ar/dona-hoy.php) da error, faltan parametros si los comparo con los botones @mkreyness 

---

## Campos del CMS

### [Evento](http://fuca3.fuca.org.ar/eventos/evento.php)
- Título
- Imágen wide de 1680x400px mínimo, 1920x1080 máximo
- Imágen chica para mostrar el evento en las demás pantallas. 234x166px mínimo
- URL página de facebook (no obligatorio)
- Fecha y hora
- Dirección
- URL mapa google
- Descripción del evento

### [Novedad](http://fuca3.fuca.org.ar/novedades/novedad.php)
- Título
- Fecha de la nota
- Imágenes del slideshow de 822x396px
- Contenido de la nota
- Etiquetas

### [Memorias y balance](http://fuca3.fuca.org.ar/quienes-somos/memoria-balance.php)
- Pasar la tabla de descargas a CMS

### Prensa - [Internet](http://fuca3.fuca.org.ar/prensa/internet.php) + [Televisión](http://fuca3.fuca.org.ar/prensa/television.php)
- Título
- URL del video
- Poder manejar el orden en que aparecen

### [Prevención - Campaña](http://fuca3.fuca.org.ar/prevencion/campanas/campana.php)
- Año (es el FUCA 2016 del html subido)
- Título
- Imágenes del slideshow de 822x396px
- Descripción

### [Home](http://fuca3.fuca.org.ar/index.php)
- Slideshow del home -> 1920x1080px es lo ideal
- Última novedad
- Último evento
- El bloque de "Qué hacemos en FUCA" tendrían que ser 4 espacios para meter foto, título, bajada y link y que pongan lo que quieran. Ahora hay links a secciones.

**Comment by mkreyness** [comment]
y esas secciones de prensa de todos modos serian homegeneas entre si en cuanto a formato ?

**Comment by mkreyness** [comment]
voy a ir armando la base de datos en "cuidatea" para lo que se sabe de estas cosas y despues voy a ir pasando las maquetas al servidor. Por ahora entonces trataremos de trabajar con el espacio que hay y despues vemos cuanto nos queda libre.

**Comment by mkreyness** [comment]
Si bien veo que "Que hacemos en FUCA" tiene 4 espacios, tambien tiene un boton que dice "Ver todo".
Eso significa que podria haber mas renglones de 4 espacios ?

**Comment by FAAREIA** [comment]
Las subsecciones de prensa van a ser distintas entre sí, algunas capas son notas, otras videos, otras links.
Lo de "ver todo" en "Que hacemos en FUCA" en realidad hay que sacarlo.

**Comment by mkreyness** [comment]
lo sacas entonces ? Todavia no pase nada al otro servidor ni arme templates.

**Comment by FAAREIA** [comment]
Ahi subí otra actualización con 2 secciones más terminadas: Misión y novedad.
Lo del home ya lo corregí.
Ojo que para subir las cosas, suelo borrar todo y resubirlo, es lo más fácil para mi por la cantidad de carpetas-subsecciones que hay

**Comment by mkreyness** [comment]
no te preocupes porque todavia no pase nada, recien hoy me avive que no estamos hablando del sitio de cuidateatiempo (en Duplika) sino de fuca.org.ar que no tengo acceso SSH todavia. Lugar hay por lo menos, pero ignoro con que me voy a encontrar una vez adentro.

**Comment by FAAREIA** [comment]
Ahi subí más y limpié el post ^^

**Comment by LeandroBraier** [comment]
@FAAREIA como venimos Fede? Pudiste avanzar un poco más rápido? Llegamos a subir todo esta semana?

@mkreyness ya pedí el SSH hoy, que me pasaron el contacto del tipo del hosting. Te aviso apenas tengo novedades.

**Comment by LeandroBraier** [comment]
Mk me dicen que ya tiene puerto SSH y es 22000

Me confirmas si pudiste acceder?

**Comment by mkreyness** [comment]
I'm IN !

**Comment by FAAREIA** [comment]
Faltan 2 pantallas que hoy ya las tenemos y luego faltan las pantallas no diseñadas o pántallas como el resto de las secciones de prensa que sin contenido no las puedo hacer, su contenido actual es inutilizable, esta todo muy chico y sin textos

**Comment by FAAREIA** [comment]
Ahi subí otra actualización, lo que faltaría hasta ahora es:

- Prensa -> Novedades
- Dona Hoy
- Prevención -> Charlas en la comunidad
- Prevención -> Eventos
- Terminar el formulario de "Voluntarios"

Ninguna pantalla faltante tiene el diseño definido y algunas no se ni que contenido van a tener como por ejemplo "Charlas en la comunidad".

**Comment by LeandroBraier** [comment]
Lo que no está en los contenidos que te mandé es porque aún no lo tenemos.
Dejemos la opción de ocultar páginas sin contenido en principio. Cuando
podemos tener la página en el servidor posta, en versión beta con CMS
funcionando?


2016-09-07 17:04 GMT-03:00 Federico Arena <notifications@github.com>:

**Comment by mkreyness** [comment]
yo estoy instalando ahora las cosas del CMS (pelado, despues tengo que pasar las tablas y cosas que habia creado sobre cuidateatiempo), a medida que pruebo puede que me salten cosas que haya que pedir que instalen. Anoche estuve dandome la cabeza contra el sitio para hacer andar un programa pero finalmente pude.

**Comment by LeandroBraier** [comment]
Buenisimo MK!

Avisame, el tipo parece piola el que administra el hosting. Se llama Adrián
Stiletano.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2016-09-07 22:21 GMT-03:00 mkreyness <notifications@github.com>:

**Comment by mkreyness** [comment]
Tiene nombre de director de cine.
Bueno necesito (no es hiperimprescindible, pero cuando quieras bajarte excels lo vamos a necesitar) que instalen el modulo perl "Spreadsheet::WriteExcel"

**Comment by LeandroBraier** [comment]
Si te parece, ya que no es tan urgente, cuando tengas algún pedido más le
paso los dos juntos, así no viciamos el canal no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
Si, por ahora es irrelevante y estoy pudiendo avanzar bien.

**Comment by LeandroBraier** [comment]
@mkreyness con CMS, ves posible que la semana que viene publiquemos la versión actual de la web (con las páginas faltantes en gris?)

**Comment by mkreyness** [comment]
Si "semana que viene" es el lunes, seguro que no. Si es mas tirando a viernes, lo veo mas posible.
Dependera tambien de que puedas cargarle en ese plazo los contenidos.

**Comment by LeandroBraier** [comment]
Si, por mi no te preocupes. Más que nada que esté subida la web online es
lo más importante para el cliente.

Entonces miércoles?

**Comment by mkreyness** [comment]
si pero lo que va a estar subido va a depender de que este cargado.
Ahora ya esta todo "online" igual que como en benteveo pero en esta carpeta:
www.fuca.org.ar/fuca3

y se ve HORRIBLE, y eso que nisiquiera empece a armar templates, es solo haber movido de benteveo a feuca.
Me parece @FAAREIA que debe estar lleno de rutas absolutas o cosas que apuntaban fuera de la carpeta fuca3 puede ser ?

**Comment by mkreyness** [comment]
no puedo andar pisando las carpetas de images y esas cosas que ya estan funcionando, por lo tanto necesitaria que todos los paths a js, css, etc. etc. sean relativos a la carpeta, y que todas esas cosas esten copiadas ahi, porque no quiero copiar cosas de mas de otros temas de benteveo.
Pegale una revisada @FAAREIA que lo que tenes en Benteveo quede funcionando encapsulado dentro de fuca3 y lo vuelvo a pasar, que no falte nada que sea necesario, asi no tengo que ponerme a investigar link por link que pasa.

**Comment by FAAREIA** [comment]
Hola Marce, uso rutas absolutas porque hay archivos .php que estan dentro de carpetas. Por ejemplo, cada item de quienes somos esta en la carpeta "quienes-somos" y asi. Lo hice de esta manera para que quede bien organizado y además no quiero tener 2 archivos includes identicos pero que uno sea "css/estilos.css" y otro "../css/estilos.css". Por eso creé un subdominio, para emular el sitio como si estuviera el root. La url de fuca debería ser http://subdominio.fuca.org.ar

Ahi subí más cosas, y aún me falta el tema del formualrio de voluntarios.

**Comment by mkreyness** [comment]
pero eso no es realista, cuando esto se quiera poner en produccion va a tener que ser www.fuca.org.ar, porque es donde la gente accede. Estamos reemplazando la home, y no puedo andar haciendo mucho truco raro porque hay un sitio existente que hasta que decidamos reemplazarlo, tiene que seguir funcionando.

**Comment by mkreyness** [comment]
Lo que podemos hacer es que si entran a www.fuca.org.ar se redireccione a [subdominio].fuca.com.ar y de ahi en mas siga en [subdominio].fuca.com.ar, pero "[subdominio]" tendria que ser algo lindo y aceptable por ellos.
Que te parece @LeandroBraier , se puede negociar ?

**Comment by LeandroBraier** [comment]
La veo difícil, nunca se habló que fuera así. Por qué necesitamos hacerlo?
No entendí la parte técnica.

**Comment by mkreyness** [comment]
@FAAREIA armo todo para que funcione en la raiz del dominio (o de un subdominio), no funciona en una carpeta. Yo no puedo reemplazar la raiz del dominio todavia, porque obviamente tiene que seguir funcionando el sitio viejo, pero necesito ver las cosas funcionando "como si" fuera el dominio.
Voy a intentar armar un subdominio para testing y despues el dia que se ponga en funcionamiento no tenemos forma de saber si se va a ver bien hasta que sea publico.

**Comment by FAAREIA** [comment]
Tiene que haber un acceso al panel de control, no solo por el subdominio, sino también para administrar los mails. @LeandroBraier 
El subdominio emula un directorio raiz, no tiene que haber problemas a futuro.

**Comment by LeandroBraier** [comment]
No entiendo @FAAREIA qué tengo que hacer yo digamos. Me pierdo en lo técnico. Necesitás un acceso al panel de control?

**Comment by mkreyness** [comment]
creo que se refiere a que debe haber una manera de definir subdominios. Si, por supuesto, yo ya lo hice y tengo eso andando en
fuca3.fuca.org.ar
Lo que digo es que el dia que "migremos" a que eso sea www.fuca.org.ar siempre puede dispararse alguna sorpresa.

**Comment by FAAREIA** [comment]
Actualicé el issue y lo limpié ^^
[Los faltantes del sitio estan al principio](https://github.com/LeandroBraier/FUCA/issues/17#issuecomment-244411085)

**Comment by FAAREIA** [comment]
Algo que me faltó preguntar:
El "formulario de donación" que es esa cosa casi irrelevante que aparece en: http://fuca.org.ar/formulario.htm es el mismo que hay que usar ahora no?
Los valores se actualizaron?
En el lugar que dice "Otro importe", cuando le doy da error. Eso hay que arreglarlo o cambiarlo?

**Comment by LeandroBraier** [comment]
El formulario es el mismo que ellos ya tenían porque lo están pagando. Mantenelo igual, yo les aviso que ese detalle les está fallando.

abrazo

**Comment by LeandroBraier** [comment]
Ahi vi los agregados en los faltantes Fede. Hoy te los paso.

abrazo

**Comment by FAAREIA** [comment]
Ahi subí una actualización de lo de FUCA (dona-hoy y becarios-exbecarios), me falta unos detalles que mañana los termino y ya estaría todo de mi parte.

**Comment by LeandroBraier** [comment]
Vamos todavía Fede!!! Ya vimos el embed también.

El cliente revisó y está muy contento. Todo lo que pidió en general es para mi por CMS, salvo algo en la dirección de FUCA que aparece en contacto, te lo paso mañana en detalle.

Mañana a la mañana voy a intentar dejar subido todo a CMS. Los otros dos faltantes ya te los actualicé en [el principio.](https://github.com/LeandroBraier/FUCA/issues/17#issuecomment-244411085)

**Consultita importante**: yo no te pasé las fotos de los becarios y por eso no tienen foto? O no tienen porque no los maquetamos con Foto?

Vamos que falta pocooo!!!

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, lo de los becarios en realidad lo hice algo diferente a lo tradicional sino había que reformular el diseño. Si vos pasas el mouse por encima del nombre de la persona, se ve su foto, si no tiene foto se ve el logo de fuca.
Igual hoy voy a mejorar unos detalles como que la foto tarda en aparecer, voy a poner algo moviendose asi parece que esta cargando.

**Comment by LeandroBraier** [comment]
Buen día Fede!

Dale, porfa. HAcelo y avisame cuando esté así le aviso al cliente. Me parece una buena resolución, pero le tengo que aclarar al cliente que lo hicimos poruqe no todos tenían foto y quedaba mal que algunos si la tuvieran y otros no. Por eso hicimos esto que es más moderno y muestra mejor en pantalla la gran cantidad de nombres. Avismae cuando esté y le aviso.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo eso: http://fuca3.fuca.org.ar/docencia/becarios-exbecarios.php

**Comment by FAAREIA** [comment]
Esta listo lo de becarios y ya esta puesto el email del formulario de contacto. Solo faltaría lo responsivo, pero primero iria siguit, luego lo responsivo de revear y finalmente fuca, no?

**Comment by LeandroBraier** [comment]
jajja En realidad las prioridades serían:

1) Siguit

2) Responsive FUCA

3) Responsive Revear

Antes igual, te pido lo que te decía ayer:
- pedir a fede: x

1) Ajustar datos de contacto FUCA 

Oficina FUCA
Conesa 1003 P. 2° (C1426AQU) CABA
(011 agregarlo que falta) 4552-0235

Stand de FUCA
Crámer 1180 (sacar el 2do piso) (C1426ANZ) CABA
(011) 4555-3555

2) sumar link al micrositio Cuidate a tiempo. Yo lo pondría arriba a la derecha como otro botón al lado de QUIERO AYUDAR que dijera CUIDATE A TIEMPO. Como lo ves?

**Comment by FAAREIA** [comment]
Ok, ahi esta listo lo de contacto y el nuevo link del header

**Comment by LeandroBraier** [comment]
Espectacular Fede!! Muchas gracias!!

**Comment by mkreyness** [comment]
@FAAREIA, por lo que veo hay muchas paginas que en si mismas no tienen contenido variable PERO llevan el aside de evento/novedad al costado. Eso es contenido variable de todos modos.
Convertir CADA pagina de esas a un template y hacer un programa que lo arme es una perdidad de tiempo atroz, lo mas razonable  seria que esos .php que se cargan por include se regeneren como todo el resto de cosas, pero no las paginas, te parece ?
Me hago un backup por si acaso y las empiezo a regenerar yo.

Otra cosa que voy a tener que hacer es tocar los links de headers (y no se si footers) para que vaya a los HTML mios en vez de los PHP en los casos de verdadero contenido variable.  Tengo que hacerlo sobre los que realmente son levantados por esas paginas, porque si no al navegar "se cruza de universo" y pasa a estar en la maqueta.
Cualquier cosa que todavia que tengas que modificar en header y footer levantate la ultima version del servidor, no pises con cosas que tengas guardadas.
Gracias

**Comment by mkreyness** [comment]
Lo que si por favor pegale una mirada @FAAREIA a esta pagina: me aparece un icono que creo que es de FB en mal lugar:
http://fuca3.fuca.org.ar/eventos.html

Esto sale del template
/www/templates/eventosT.html

fijate si descubris que hay que tocar y si podes arreglalo o decime.
Si tocas el template teoricamente en 5 minutos se ajusta la pagina html

**Comment by LeandroBraier** [comment]
@mkreyness ya cargué en el CMS Memoria y Balance. Mañana a la mañana cargo slideshow, novedades, eventos y charlas a la comunidad. Cuando se va a ver impactado eso en la web? 

@FAAREIA mañana porfa revisá este ticket con lo que te pide MK.

abrazo

**Comment by mkreyness** [comment]
JUSTO memoria y balance todavia no lo hice, pero lo hago esta noche.

**Comment by LeandroBraier** [comment]
Dale, todo bien. Abrazo

**Comment by mkreyness** [comment]
listo Memoria y Balance

http://fuca3.fuca.org.ar/quienes-somos/memoria-balance.html

**Comment by mkreyness** [comment]
Ahora estoy con el formulario de voluntarios.
En serio quieren poner pais/provincia/localidad/codigo postal/domicilio en ese orden ?
Es tan antinatural... Yo entiendo que conviene si es que va a ir un autocompletar en la localidad, pero eso solo lo puedo hacer si es Argentina, y el desplegable de provincias no tiene sentido si eligen otro pais, deberia ser tambien algo tipeable, @FAAREIA

**Comment by mkreyness** [comment]
otra cosa que no veo bien es el tema de los checkboxes de estudios, deberian ser excluyentes, no tiene sentido marcar mas de uno, deberia ser "maximo nivel de estudios" o algo asi y funcionar como radiobuttons.

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Gracias! Ya vi Memoria y Balance actualizado. Ya cargué Slideshow y funciona OK. 

Cargué Novedades y levanta bien los listados pero no las notas. Además no levanta la última en cuanto a fechas sino la última cargada en el CMS. Necesito que siempre muestre la de fecha más reciente. Fijate qué puede ser porfa.

Eventos subí y parece todo ok, cargué 1. Corrijo. Se subió y se ve así: http://fuca3.fuca.org.ar/eventos/el-arte-esta-de-moda-con-fuca-en-hilton-buenos-aires.html
Bastante bien no? Solo que el texto quedó hecho una mancha no sé por qué.

Charlas de la Comunidad tengo para cargarlas pero no encuentro donde. Me dicen?

@FAAREIA estimé los tamaños de imagen más o menos pero cuando puedas me pasás los tamaños exactos que tienen que tener cada una de las imágenes?

abrazo

**Comment by mkreyness** [comment]
Ahora reviso todo. Lo del texto es un tema de si lo que pusiste en el HTML esta o no metido dentro de un parrafo.
Eso de las charlas ni sabia que era variable, Lo agrego al CMS, lo templatizo y te aviso.

**Comment by mkreyness** [comment]
texto del evento y que la home muestre la novedad de fecha mas reciente ya esta arreglado, en cuanto se republique todo lo vas a ver bien.

**Comment by mkreyness** [comment]
Las "novedades" llevan texto HTML y encima un slideshow propio, como no le cargaste nada no te aparece nada.
Fijate la que hice yo de prueba, tiene cosas en la solapa "Texto HTML" e "Imagenes".
Cuando lo completes te va a aparecer.
La BAJADA de la novedad solo se pone en la lista, la idea es que el contenido (como siempre fue en las novedades de Parex, etc.) es una cosa HTML mucho mas elaborada.

**Comment by mkreyness** [comment]
De hecho "Charlas a la Comunidad" esta grisado en el menu, me daria la impresion de que no esta hecha la maqueta todavia ???

**Comment by LeandroBraier** [comment]
OK, charlas a la comunidad queda esperando a Fede entonces. Yo avanzo con
lo que me decís de la nota HTML. Gracias por todo!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness ahí le cargué todo como pediste. Consulta: por qué después de la fecha aparece la palabra "hs" ? Se puede quitar?

<img width="321" alt="captura de pantalla 2016-09-15 a las 12 57 16 p m" src="https://cloud.githubusercontent.com/assets/6719872/18555961/301f84c4-7b40-11e6-8982-c7016f086d77.png">

**Comment by LeandroBraier** [comment]
@mkreyness me dice @FAAREIA que campañas también debería poder cargarlo por CMS. Te alisto los pendientes entonces

# Pendientes

1) ¿por qué después de la fecha aparece la palabra "hs" ? Se puede quitar?

<img width="321" alt="captura de pantalla 2016-09-15 a las 12 57 16 p m" src="https://cloud.githubusercontent.com/assets/6719872/18555961/301f84c4-7b40-11e6-8982-c7016f086d77.png">

2) Habilitar en CMS para subir Charlas en la Comunidad y Campañas.

abrazo

**Comment by mkreyness** [comment]
Eso que pusiste en 1) que es, un evento ? No se supone que van con fecha y hora ? Capaz no le cargaste la hora.
2) Ok, busco las maquetas y agrego al CMS

**Comment by LeandroBraier** [comment]
1) Es que justo este evento no es un día y horario específico. Es desde el 6/09 al 17/10 y durante todo el día en el Hilton. No se podrá hacer que no muestre la hora si no está cargada y que muestre un "desde" y "hasta" en fecha y hora?
2) Gracias!

**Comment by mkreyness** [comment]
te pongo un campo de texto entonces para que escribas lo que quieras y listo ? Cuando sea hora, sera hora, cuando sea un rango horario lo escribis vos como mas convenga.

**Comment by LeandroBraier** [comment]
Excelente! Con eso perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-09-15 17:08 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Me colgué con siguit y me había olvidado de esto...
- Ok con hacer algunas bloques del aside variables
- Eventos ya lo arreglé. La imagen no la encuentra igual, esta mal la url
- En voluntarios, puse ese orden por si es de otro país, que se yo. Si elije otro país, fijate que en el HTML hay un campo oculto de "provincia-otra" (creo que era asi), justo seguido del provincia default.
- En voluntarios los estudios los dejarían como estan, uno puede tener un título universitario en una carrera y un terciario en otra, no me parecería un caso muy raro ese.
- Los tamaños de las imágenes estan en [al principio](https://github.com/LeandroBraier/FUCA/issues/17#issuecomment-244411085) de este issue
- Lo de charlas en comunidad mandame el contenido asi lo veo y hago la maqueta, nunca vi el contenido salvo el de la web que es inusable

**Comment by LeandroBraier** [comment]
@FAAREIA te referís a mi por el contenido?

Yo ya cargué las charlas como Novedades. Si se pudiera hacer que etiquete a algunas novedades como Charlas y que esas solas figuren en dicha sección, no sería más fácil?

Mirá:

http://fuca3.fuca.org.ar/novedades-1.html

En cualquier caso la maquetación sería similar a la de novedades.

Tamaños de las imágenes: gracias!! Lo había olvidado.

**Comment by mkreyness** [comment]
De hecho YA ETIQUETASTE esas novedades como charlas, entonces "Charlas" es simplemente el url de la etiqueta "charla":
http://fuca3.fuca.org.ar/novedades/etiqueta-charla.html

**Comment by LeandroBraier** [comment]
Exacto! Ya les cargo la etiqueta a todas las que corresponden por las dudas.

**Comment by mkreyness** [comment]
@LeandroBraier lo del campo de texto para rango horario ya esta habilitado.

**Comment by FAAREIA** [comment]
Perfecto entonces.
Lea queres eliminar el link de charlas a la comunidad o que vaya a las novedades etiquetadas como "charlas"?

**Comment by mkreyness** [comment]
yo ya toque el header para que el menu "Charlas" vaya a esa etiqueta, no hay que tocar mas nada.

**Comment by mkreyness** [comment]
Pero veo que ahora esta deshabilitado... Lo pisaste ? Antes me andaba perfecto.
Lo que me queda pendiente es 
- lo de que los asides php de contenido variable se regeneren solos, 
- terminar con el formulario de voluntarios, que ademas veo que tengo que agregarle un lugar para cargar el slidehow
  lo que me decias de que si no pones Argentina se cambia el campo no lo veo funcionando, yo pongo  Botswana y me siguen apareciendo las provincias (que como siempre ademas falta CABA, igual eso lo voy a reemplazar por la codificacion que tengo en base de datos)

**Comment by FAAREIA** [comment]
Hola Marce, no ni me metí al FTP y recién lo chequié y lo vi funcionando ese link.
Lo del país no esta hecho, simplemente lo dejé preparado para que si el país no es argentina le metas o le saques la clase "hide" a uno u otro div contenedor de localidad.

**Comment by mkreyness** [comment]
Que raro, a mi "Charlas" me aparece disabled, no estará en mas de un menú?

Ok, manejo yo esos campos por JavaScript entonces

**Comment by FAAREIA** [comment]
Te digo lo que acabo de ver:
- http://fuca3.fuca.org.ar/novedades/etiqueta-melanoma.html tiene el link ese DEShabilitado (sin link)
- http://fuca3.fuca.org.ar/novedades-1.html tiene el link HAbilitado

Me imagino que el problema que genera eso debe ser el mismo que genera que el bloque de etiquetas sea diferente en los 2 links esos

**Comment by mkreyness** [comment]
es el temade las etiquetas que se generaron con/sin blanco delante (como lo de cancer que te aparecia dos veces). Unos quedaron generados con el header viejo. Voy a borrar todas y que se regeneren. Las que falten, es porque hay alguna otra cosa mal que tengo que revisar.
