### ISSUE TITLE
Últimos ajustes de contenido de Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#18]
@FAAREIA te paso los ajustes de web FUCA por acá así quedan por fuera del ticket tan largo que tenemos.

El cliente pidió unos ajustes mínimos de texto en sección Contacto (creo que solo vuela la palabra "sin fines de lucro" y "exclusivamente" pero revisá por las dudas).

**CONTACTO**

Contáctenos:

La Fundación Cáncer – FUCA es una entidad de bien público (Inscripción I.G.J. nº 33) que realiza su obra con recursos provenientes de aportes particulares, no recibe subsidios regulares de fondos estatales. Los donantes de FUCA pueden realizar deducciones impositivas porque se encuentra enmarcada en lo dispuesto por el Art. 81, Inc. c) de la Ley 20.698.

Dirección:
Conesa 1003 P. 2, C.A.B.A. (C1426AQU), Argentina

**Comment by FAAREIA** [comment]
Hecho, hoy cuando suba más cosas ya va a estar.

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by mkreyness** [comment]
@FAAREIA avisame cuando ya no toques mas asi lo paso todo al servidor de Fuca y empiezo a armar los templates.
