### ISSUE TITLE
Últimos ajustes Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#19]
@FAAREIA revisé toda la web y te paso últimos ajustes:

1- PERFORMANCE: Tarda mucho en cargar, por qué puede ser?

2- HOME: Borrar el número que dice FAX en el footer y borrar el texto "Loren Impsum del botón rojo de QUIERO CONTRIBUIR POR UN MUNDO SIN CANCER

3- DONÁ HOY: Me piden actualizar las cifras del formulario y ponerlas "desordenadas" de la siguiente manera:

$100 / $50 / $200 / $75

4- MISIÓN: El texto principal está chiquito y pisa la imagen. Pongamoslo junto con el otro por favor, porque no se lee. Me refiero a **"La Fundación Cáncer – FUCA (Fundación para la Investigación, Docencia y Prevención del Cáncer), es una organización de la sociedad civil creada en 1983 por los Dres. Reinlado Chacón y José Mordoh, inscripta en la I.G.J. con el N° 33."**

5- CAMPAÑAS: ¿Por qué no están cargadas las campañas que están en la página actual? Deberían estarlo porque eso no tiene carga por CMS. El cliente se ve que no revisó bien y no lo vio. 
http://fuca3.fuca.org.ar/prevencion/campanas.php
http://fuca.org.ar/campanas.htm

6- INFORMACIÓN SOBRE EL CÁNCER: Piden cambiar la foto que usamos de fondo del slideshow, porque esas cintas representan solo a 1 tipo de cáncer. Se me ocurre reemplazarla por esta: http://biology.usf.edu/cmmb/images/cells2.jpg Si se te ocurre otra mejor todo bien.

Solo eso.

Dejo [este ticket ](https://github.com/LeandroBraier/FUCA/issues/17#issuecomment-247127080) para todo lo técnico que tiene que ver con el CMS.

abrazo

**Comment by FAAREIA** [comment]
Las campañas iban por CMS según el detalle de [este issue](https://github.com/LeandroBraier/FUCA/issues/17). ¿Las pongo a mano? Por otra parte, muchas van a necesitar un recorte de fotos o nuevas fotos porque el formato que tienen a veces no sirve ni para thumbnail

**Comment by LeandroBraier** [comment]
Ok, le pido a MK que me las habilite en el CMS porque hoy no están.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-09-15 14:15 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Repaso:
1. El tema de la performance, o es su conección o el servidor en ese momento. A mi me anda perfecto a veces y otras se queda pensando sin motivo, lo cual estimo que es un problema del hosting. No hay razón por la que debería de tardar en cargar, es una página bastante liviana en general.
2. Borré fax y reemplacé texto porque sin texto queda mal
3. Dona hoy -> hecho
4. Misión -> Hice más visible el texto....si lo pongo abajo se va de caja con respecto a la foto del costado
5. Campañas -> va por cms
6. Info cancer -> dale F5 para ver la foto nueva

**Comment by LeandroBraier** [comment]
Todo perfecto Fede!! Muchas gracias!
