### ISSUE TITLE
Últimos cambios en Web de FUCA 19/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#20]
@FAAREIA el cliente me pidió cambios nuevos, así que le estoy diciendo que van a estar para el lunes. Todas cositas muy puntuales y un pequeño ajuste de maquetación.

1) FORMACIÓN MÉDICA: http://fuca3.fuca.org.ar/docencia/formacion-medica.php

Quitar la Residencia Básica en Diagnóstico por imágenes. O, si no se puede, ponerle "Próximamente" en lugar del contenido. 

2) PUBLICACIONES CIO: http://fuca3.fuca.org.ar/investigacion/publicaciones-cio.php

Se suma 1 publicación de 2016:

Standardization of molecular monitoring for chronic myeloid leukemia in Latin America using locally produced secondary cellular calibrators
[leu2016197a.pdf](https://github.com/LeandroBraier/FUCA/files/477666/leu2016197a.pdf)

3) MEMORIA Y BALANCE: http://fuca3.fuca.org.ar/quienes-somos/memoria-balance.php

Te envío las memorias 2014 y 2015, y el balance 2014 que necesito que subas y me pasas la URL para subirla al CMS:

[FUCA memoria 2014.pdf](https://github.com/LeandroBraier/FUCA/files/477669/FUCA.memoria.2014.pdf)
[FUCA memoria 2015.pdf](https://github.com/LeandroBraier/FUCA/files/477670/FUCA.memoria.2015.pdf)
[Balance 2014 Completo.pdf](https://github.com/LeandroBraier/FUCA/files/477671/Balance.2014.Completo.pdf)

4) INTERNET http://fuca3.fuca.org.ar/prensa/internet.php

Falta subir estos 2 videos:
https://vimeo.com/111979552 (Campaña Corro con Jonás 2014)
https://vimeo.com/110461977 (Cuidate a Tiempo 2014)

5) TELEVISIÓN http://fuca3.fuca.org.ar/prensa/television.php

Quitar el video del chino y sumar estas 2 entrevistas:

https://youtu.be/f8GLibAHG14 (Día Mundial contra el Cáncer en C5N Febrero 2016)

https://www.youtube.com/watch?v=vibB0uYek-E (Cuidarse está de moda Canal 9 Agosto 2016)

6) BECARIOS 

Falta las fotos de los dos de primer año (te envío fotos). 

![dra romina luca](https://cloud.githubusercontent.com/assets/6719872/18600682/5f62ef28-7c35-11e6-9055-0baf670bb6c3.jpg)
![dr -cristian-alexis-ostinelli](https://cloud.githubusercontent.com/assets/6719872/18600684/60970f14-7c35-11e6-972a-8ce1123c8836.jpg)

Y colocar el nombre de Dra. Lucía Fuente (Sin foto)

7)  CHARLAS A LA COMUNIDAD Piden que hagamos un template donde estén subidas todas las charlas alistadas, pero ordenadas por fechas, como en la página de eventos. Esto va a exigir unos pequeños ajustes de maquetación. 

Después adentro la charla podría seguir siendo la misma nota de Novedades, pero necesito poder poner un embed de YouTube en cada una. Probé con el editor HTML del CMS y no me dejó. Esto me parece que sería un trabajo para @mkreyness 

abrazo y buen finde!

**Comment by mkreyness** [comment]
ya arregle 8)

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Puede ser que en la home no se vea la fecha y se superpongan los iconos de fecha y lugar?

**Comment by mkreyness** [comment]
ahora reviso, capaz esta roto algo en el template

**Comment by mkreyness** [comment]
listo, no me avive que la home es diferente al resto, no lo tiene como un aside sino que es parte de la maqueta principal. Fijate ahora sale bien.

**Comment by LeandroBraier** [comment]
Gracias MK! Hermoso!!

Solo se pisa un poco con botón grande y rosa de abajo, pero eso lo podemos resolver el lunes tranqui.

@FAAREIA y @mkreyness les quiero decir que miro la web y me emociono, después de más de 6 meses de comenzada. No lo puedo creer que ya casi esté jeje Gracias a los dos!!!!

**Comment by mkreyness** [comment]
lo del reemplazo automatico de asides en las paginas de contenido no-CMS ya se esta haciendo tambien.
Solo me queda terminar lo del formulario de voluntarios (vale la pena o al cuete los slides de voluntarios por CMS?)

**Comment by LeandroBraier** [comment]
Vale la pena MK. Tenemos fotos de los voluntarios.

Che prensa no va a estar en el cms al final?

**Comment by mkreyness** [comment]
Si ya se, pero no son fotos fijas ? Si es por eso habria que pasar al CMS las fotos de los directivos, los becarios, etc. No tengo idea que hacer con prensa, lo maquetaste Fede ?

**Comment by LeandroBraier** [comment]
Solo preguntaba pero ya le pasé  a fede los contenidos para que los pase a
mano. No te preocupes.

Lo de las fotos no hace falta para directivos y demás. Sigamos la
maquetación de fede para voluntarios porfa.

**Comment by mkreyness** [comment]
ya esta el CMS para las fotos de voluntarios y ya las cargue todas, ahora estoy terminando un par de pavadas y ya dejo el formulario funcionando a full.

**Comment by mkreyness** [comment]
listo, ya esta el formulario andando y se pueden extraer los resultados por el CMS

**Comment by FAAREIA** [comment]
Repaso los puntos:

1. Hecho
2. Hecho
3. Va por CMS
4. Va por CMS
5. Va por CMS
6. Hecho
7. Ok, son 2 templates nuevos asi la fecha y ubicación tienen mejor presencia.

**Comment by LeandroBraier** [comment]
Muchas gracias a ambos!!

@FAAREIA 

1) Gracias! Solo quitale esta frase: "En breve estaremos subiendo los contenidos correspondientes." Dejale "Próximamente" solo. No es un tema de contenidos, sino que la residencia aún no se abrió jeje

2) Perfecto!

3) Si, ya lo sé, pero necesito los links Fede! No puedo subir PDF al servidor yo solo. Si me lo permiten lo hago.

4) @mkreyness avisame cuando esté habilitado. No veo donde cargarlo.

5) @mkreyness avisame cuando esté habilitado. No veo donde cargarlo.

6) Gracias!!

7) Ok, gracias Fede! Avisame para cuando lo podemos tener pero si no está hoy no hay problema. Dejá en Gris el Link de Charlas para la Comunidad simplemente.

abrazo

**Comment by mkreyness** [comment]
De prensa no hice nada, estaba esperando el ok de que todo estaba maquetado y me avisaran cuales llevaban contenido variable.

Son estas entonces ?

4) INTERNET http://fuca3.fuca.org.ar/prensa/internet.php

5) TELEVISIÓN http://fuca3.fuca.org.ar/prensa/television.php

es para poner URLs, no para uplodear videos, no ?

**Comment by LeandroBraier** [comment]
Sip, entiendo que si MK.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
ahora hago eso entonces. En un rato te aviso

**Comment by mkreyness** [comment]
listo, ya esta en el CMS e implementado. Puse de demo algunos que ya estaban, pero cambialos.
Deje previsto (aunque no esta en la maqueta) por si quieren en algun momento ponerle un texto de bajada a los videos, mas alla del titulo. Por ahora no se usa.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Ahora a la tarde lo pruebo y subo.

@FAAREIA me piden una nueva tanda de cambios.

1) Reordenar los items en los menues:

·         QUIENES SOMOS: Misión > Autoridades > Staff > Voluntarios >Memoria y balance> Historia

·         CIO: Presentación > El resto igual > Premios y presentaciones (ante último) > Historia (última)

·         DOCENCIA: Formación médica > Becarios y Ex becarios > Biblioteca

·         PRENSA: Novedades arriba

2) DONACIONES: Está mal escrita Master, en tarjetas de crédito y débito. Sugirió que tanto Master como Amex, lleven los nombres completos: Mastercard / American Express

3) AULAS ABIERTAS: Quitar el mail aulas@fuca.org.ar y colocar administración@fuca.org.ar / Sacar el acento en Álvarez

4) CIO: agregar a Maestranza Drennen Daniela Margarita y corregir el apellido de Silvana Ribelle

5) ·MEMORIA Y BALANCE: Reordenar del último al más viejo.

@mkreyness me está pasando un BUG marca cañón. Quiero guardar una foto en el evento de la Charla del Dr Chacón y al guardar me lleva a la web y no me guarda un carajo. Te fijás qué es?

http://fuca3.fuca.org.ar/cgi-bin/fuca.pl?item=abm.evt&itembusqueda=abm.evt&accion=editar&id=3&busqueda=17&uniqueid=&pagina=1&menu=1&abiertos=16

**Comment by mkreyness** [comment]
No sera como siempre que la foto tiene acentos o bichos raros en el nombre ?
Recien probe (y de paso habilite para poder hacerlo desde la lista sin tener que entrar a la novedad) de agregar un par en la mia de prueba, y la que tenia acentos tuvo problemas y la que no, no.

**Comment by LeandroBraier** [comment]
portada-chacon-septiembre-fuca.jpg era el nombre. No tiene nada raro. 

Volvi a hacer lo mismo con nombre mas corto y volvió a pasar lo mismo. Me lleva a la web.

**Comment by mkreyness** [comment]
Proba desde la lista de novedades, haciendo click en "[x] imagenes" para agregarlos directo ahi.
Ahi a mi me anduvo perfecto, fijate todas las que hay en la primera (suspendida) hay una bien y una rota, porque decia "nenúfares.jpg" asi con acento.
Cuando decis "me lleva a la web" exactamente que significa ? Te abre una ventana de un browser en blanco ???

**Comment by FAAREIA** [comment]
Los campos de lo de internet y television estan [definidos aca](https://github.com/LeandroBraier/FUCA/issues/17#issuecomment-244411085), en ese post esta la base para armar las secciones administrables

**Comment by LeandroBraier** [comment]
@mkreyness no entiendo lo que decís que haga, yo estoy cargando en "Evento". Te paso captura en vivo de lo que me ocurre así me entendés:

[Para mk.mp4.zip](https://github.com/LeandroBraier/FUCA/files/480764/Para.mk.mp4.zip)

**Comment by FAAREIA** [comment]
@mkreyness en el punto 3 necesito que Lea pueda subir PDFs sino es como que es medio al dope que quede autoadministrable esa sección, se podrá?

**Comment by mkreyness** [comment]
AHHH como me dijiste charla pense que era lo que salia en el menu "Charlas a la Comunidad" que no es mas que una etiqueta de NOVEDADES, con razon me andaba bien. Ahora me fijo.

**Comment by mkreyness** [comment]
Me pasas la foto que queres subir asi pruebo todo igual ?

**Comment by mkreyness** [comment]
@FAAREIA: no tengo implementado un repositorio de archivos genericos en mi CMS para hacer upload de cualquier cosa, solo imagenes y video, tendria que hacer una extension del mismo que va a llevar un tiempo. Ademas hay que ver si en ese hosting (que no se ni quienes son) siendo un servidor compartido permiten hacer upload de cualquier tipo de archivos via web, seria una falla de seguridad importante.
No es como el FTP que esta "enjaulado"

**Comment by LeandroBraier** [comment]
Dale, te la paso acá @mkreyness 

![chacon-septiembre-fuca](https://cloud.githubusercontent.com/assets/6719872/18645867/61da93da-7e85-11e6-9534-7d8acb653ba5.jpg)

**Comment by mkreyness** [comment]
mira, tiene que ser algo corrompido en el archivo, algo que hace que el Apache del servidor lo rechace, porque con cualquier otra foto que subo, anda bien.
Lo que hice ahora fue abrirlo con el Paint y guardarlo con otro nombre, y me lo tomo bien.

**Comment by mkreyness** [comment]
@FAAREIA algo se rompio en el CSS, mira como sale ahora el php de eventos (en el html mio pasa parecido pero no igual)

![facebook-roto](https://cloud.githubusercontent.com/assets/6135791/18646318/601a6c26-7e87-11e6-8268-9c6de185c296.JPG)
![todo-roto-en-el-php](https://cloud.githubusercontent.com/assets/6135791/18646340/7782e7c6-7e87-11e6-8c02-0ed2aefbb7ed.JPG)

**Comment by FAAREIA** [comment]
Ahi borré un par de post ya respondidos, sino rastrear las cosas es un laberinto.
- Lo de memorias OK, todavia me falta hacerlo. @mkreyness aca solo sería subir PDF no va haber problema con el hosting. Imagino que si es mucho tiempo Lea tendría que definir si vale la pena hacerlo
- Template de charlas en comunidad -> http://fuca3.fuca.org.ar/prevencion/charlas-comunidad.php Es igual a eventos pero no tiene lo del facebook y tiene páginado porque son 6 por página.
- El template de la charla en si es el mismo que el del evento que le ajusté unas cosas y le agregué un slideshow. Lo que habría que tener en cuenta es que ahora el botón del facebook puede no estar y que el slideshow puede no estar. @mkreyness 
- El css lo actualicé, denle F5
- @LeandroBraier el punto 4 del segundo post no lo encontré, no se que url es

**Comment by mkreyness** [comment]
ya di F5 muchas veces y no se arregla, sigue igual que como las fotos que pase.
No habiamos dicho que "charlas" era la etiqueta "charla" de las novedades ?

**Comment by FAAREIA** [comment]
Se tiene que renovar el template, le agregué una clase en novedades y eventos.
Charlas no es novedades ahora porque necesita fecha y ubicación.......y sería igual a eventos pero no tiene FB y tiene paginación ^_^

**Comment by LeandroBraier** [comment]
@mkreyness es un pedido nuevo que hizo el cliente el viernes. FIjate en este ticket más arriba.

**Comment by mkreyness** [comment]
Ah, ok, bueno, entonces necesitas un CMS aparte para las charlas ? O vas a cargarlas como eventos y les ponemos una marquita de que tambien se muestre en charlas ?

**Comment by FAAREIA** [comment]
Bueno ya esta todo **excepto el punto 4 del segundo post de este issue** que no lo encuentro, pasame la url cuando puedas.

Lamentablemente lo de memorias y balance hay que rehacerlo, no puede reordenarse y los links actuales apuntan al sitio viejo y no son s-a-f-e. La lista nueva sería:
/docs/memoria-balance/2005-memoria.pdf
/docs/memoria-balance/2006-balance.pdf
/docs/memoria-balance/2006-memoria.pdf
/docs/memoria-balance/2007-balance.pdf
/docs/memoria-balance/2007-memoria.pdf
/docs/memoria-balance/2008-balance.pdf
/docs/memoria-balance/2008-memoria.pdf
/docs/memoria-balance/2009-balance.pdf
/docs/memoria-balance/2009-memoria.pdf
/docs/memoria-balance/2010-balance.pdf
/docs/memoria-balance/2010-memoria.pdf
/docs/memoria-balance/2011-balance.pdf
/docs/memoria-balance/2011-memoria.pdf
/docs/memoria-balance/2012-balance.pdf
/docs/memoria-balance/2012-memoria.pdf
/docs/memoria-balance/2013-balance.pdf
/docs/memoria-balance/2013-memoria.pdf
/docs/memoria-balance/2014-balance.pdf
/docs/memoria-balance/2014-memoria.pdf
/docs/memoria-balance/2015-memoria.pdf

**Comment by mkreyness** [comment]
y yo sigo viendo todo roto el CMS de eventos.php, vos hace que ande ahi y yo veo si tengo que ajustar algo en mi template (o si queres ajustarlo vos, esta en /templates/eventosT.html).

**Comment by mkreyness** [comment]
ya agregue un tilde de si es charla o no en los eventos, y la posibilidad de cargar un slideshow, ya funciona.
Ahora si no se pone nada en el link a facebook el cartel de facebook desaparece.
Me queda agregar paginacion en la (valga la falsa redundancia) la pagina de eventos y el filtro de "solo charlas".

**Comment by mkreyness** [comment]
ya esta la paginacion en eventos, y el filtro, y esta actualizado en el menu que en "Charlas" muestre la primer pagina de los eventos filtrados por charlas.
Como en total hay 2 eventos cargados, la paginacion no se puede probar por ahora.
Lo unico que queda feo es que entrando por "charlas" dice "EVENTOS" bien grande, lo puedo parametrizar y que diga "CHARLAS", les parece ?

**Comment by LeandroBraier** [comment]
Si, por favor. Gracias!

**Comment by mkreyness** [comment]
Listo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

**Comment by LeandroBraier** [comment]
@FAAREIA el punto 4 que te falta es agregar dentro de esta página:

http://fuca3.fuca.org.ar/investigacion/presentacion.php

a la Maestranza Daniela Margarita Drennen.

La otra Silvia Sibelle no la encuentro yo tampoco.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness estoy viendo que la sección campañas no levanta el texto HTML subido en el CMS. Sube un texto cualquiera que es igual en todas las campañas. Te fijás porfa?

http://fuca3.fuca.org.ar/campanas.html

**Comment by mkreyness** [comment]
debe haber quedado fijo en la maqueta, ahora reviso en un rato.

**Comment by mkreyness** [comment]
ahi lo arregle pero la ultima (qutilipi) no se generaba. Ya lo arregle tambien.

**Comment by LeandroBraier** [comment]
Gracias! pero por qué no se generaba?

**Comment by mkreyness** [comment]
error en el programa que estaba mirando cuantas novedades habia en vez de cuantas campañas (hay menos novedades que campañas), entonces paraba antes. Cosas de andar copiando y pegando codigo de un programa a otro.

**Comment by LeandroBraier** [comment]
Ah perfecto.  Me quedo tranquilo entonces. Hoy termino de subir todo
entonces. Gracias!

**Comment by FAAREIA** [comment]
Lo del punto 4 sigue raro, tengo que agregar a Maestranza Drennen Daniela Margarita pero no nos dijeron en que parte, no se si es tesista o subdirectora o qué

**Comment by LeandroBraier** [comment]
¿No sabés lo que es Maestranza Fede? Ponela junto a la gente de
administración y demás. Es personal de limpieza, no es un perfil académico
ni científico

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahora si me queda claro ^^, ahi lo subí

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Uh, yo casi me estaba anotando pars Maestranza de la Universidad San Andres creyendo que era lo mismo que una Maestria,  entonces lo que yo creia que era el precio era el sueldo ofrecido ? Ya me parecia que los conocimientos en separacion de residuos y pulido de bronces que ponian como requisito eran demasiado.

**Comment by LeandroBraier** [comment]
Listo, ya cargué todo. Muchas gracias chicos!!

Revisé y lo único que veo que falta es que EVENTOS del menú PREVENCIÓN sigue en gris. Lo demás ya está!

Muchas gracias!! Ahora espero que el cliente nos confirme para hacer la migración al root del dominio. 

@mkreyness un par de consultas:
1)  tenemos todo listo para hacer eso? 
2) Si lo hacemos se borra toda la web vieja o se puede dejar por un tiempo guardada por las dudas?

**Comment by mkreyness** [comment]
Adonde deberia llevar ese "eventos" del menu prevencion ? A lo mismo que el "eventos" que esta directo en el menu ? Nunca entendi por que habia 2.

1) teoricamente, si. No deberia hacer falta mover fisicamente nada, sino reapuntar desde el CPanel a que el sitio www apunte al directorio fuca3 
2)  No se borra nada, solo deja de estar accesible via www.
3) la duda es que no se que pasaria si la gente no escribe www, pero de ultima lo que dije recien es rapidamente reversible si no sirve.

**Comment by LeandroBraier** [comment]
No recuerdo tampoco. Quitemoslo directamente si se puede. Sino que lleve al mismo que el "eventos" directo del menú.

1, 2 y 3) Perfecto! Esperamos feedback del cliente entonces.

abrazo

**Comment by mkreyness** [comment]
listo, "eventos" en "prevencion" lo comenté, si hace falta lo recuperamos.

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness  últimos cambios y ya lanzamos!

1) En Autoridades, consejo, cambiá la foto de del Dr Chacón por la misma q pusimos en el slideshow:

http://fuca3.fuca.org.ar/quienes-somos/autoridades.php

<img width="1006" alt="dr -reinaldo-chacon-fuca-3" src="https://cloud.githubusercontent.com/assets/6719872/18757846/f58359a8-80cb-11e6-83e5-90ba747e329a.png">

2) En el CIO, presentación: corregir lo siguiente:

http://fuca3.fuca.org.ar/investigacion/presentacion.php
- agregar Secretaria de dirección: Silvana Ribele 
- corregir Secretaria Administrativa: Carolina Bernal (va con una sola L)

3) @mkreyness cuando entro a:

http://fuca3.fuca.org.ar/

no me aparece lo mismo que cuando entro a:

http://fuca3.fuca.org.ar/home.html

Lo que debería quedar es la segunda, que responde al CMS. Asegurate porfa de que cuando migremos al root de la URL se migre el correcto.

abrazo

**Comment by LeandroBraier** [comment]
Con estos cambios aplicados, @mkreyness, ya migramos la página.

**Comment by mkreyness** [comment]
3) listo, fijate.
Avisame cuando este todo lo demas OK asi hago la migracion.

**Comment by LeandroBraier** [comment]
3) Perfecto!

1 y 2) Espero a @FAAREIA !

Vamos que salimos!

**Comment by FAAREIA** [comment]
Perdón por la espera pero sigo sin internet en casa y ayer se lo dediqué a siguit que ahora en un rato lo subo completo.
Todo listo ^^

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!

@mkreyness tenemos el OK para lanzar y pasar a producción! Me avisás cuando esté porfa?

abrazo y graciasa  los dos!

@FAAREIA ahora a seguir con el responsive de FUCA no?

**Comment by FAAREIA** [comment]
Estoy por terminar siguit y sí, sigo con eso y después revear. Hay para rato ^^

**Comment by LeandroBraier** [comment]
Dale, genial jeje Así es @FAAREIA Gracias!

abrazo

**Comment by mkreyness** [comment]
Me parece lo mas prudente hacer el cambio a la noche tarde cuando haya menos gente mirando, por si algo sale mal, y hubiera que hacer ajustes, no ? 
O si queres lo hago hoy a las 4 cuando llego, pero si algo sale mal solo voy a poder volverlo atras, reajustar, y reintentar N veces.
Dejandolo para la noche puedo arreglar directamente sobre lo roto e ir ajustando hasta que ande, sin volver atras.

**Comment by LeandroBraier** [comment]
Ok. Para decidir eso decime los riesgos. Hay mucha posibilidad de que se
rompa?

**Comment by mkreyness** [comment]
No lo puedo saber hasta que sea demasiado tarde.

**Comment by LeandroBraier** [comment]
Ok. Hagamoslo a la noche entonces. Le aviso al cliente que va a ser asi.
Gracias!
El 23 sept. 2016 13:51, "mkreyness" notifications@github.com escribió:

No lo puedo saber hasta que sea demasiado tarde.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/LeandroBraier/FUCA/issues/20#issuecomment-249244504,
or mute the thread

**Comment by mkreyness** [comment]
Listo, menos mal porque me encontre un monton de sorpresas desagradables.
No me dejo poner "www." como subdominio, con lo cual desde el CPanel no habia como hacer que el www. (y menos aun el fuca.org.ar sin nada) apuntaran a la carpeta del fuca3.
Hice un backup de todo igual antes de tocarlo (esta en un archivo ahi mismo en el servidor, se llama public_html.tar.gz por si queres levantarlo Fede, pesa apenas 1.5 Gb.
Finalmente la cosa quedo solucionada mediante una serie de trucos feos, el public_html lo renombre como "expublic_html" e invente un link "public_html" que apunta a "expublic_html/fuca3", e hice los ajustes dentro de mi programa para que no busquen ni graben mas en lugares "fuca3".
Finalmente revisando todo encontre que algunos links de los menues y del footer estaban mal, porque no tenia que apuntar a novedades.html y eventos.html sino a novedades-1.html y eventos-1.html, ya que se genera un archivo por cada pagina, y la primera (aunque sea la unica) de cada cosa se llama "-1.html". 
Creo que esta andando todo bien, pero peguenle una revisada.

**Comment by LeandroBraier** [comment]
Muchas gracias MK! Ahora lo reviso todo y te confirmo. Abrazo

**Comment by LeandroBraier** [comment]
Muchas gracias @mkreyness ! Quedó excelente. Ya revisé todo, mandé mensaje por formulario y todo.

abrazo grande y felicitaciones a los dos! Quedó una excelente web.

Abro un ticket aparte para el responsive nomás.
