### ISSUE TITLE
Responsive Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#21]
Abro este ticket solo por cuestiones del responsive y para que me avises cuando ya esté listo nomás.

abrazo grande

**Comment by FAAREIA** [comment]
Agrego algo:
1. Todos los meta description de todas las páginas ×_×
2. Definir el open graph global del sitio. Osea, que el tipo que comparta la Historia de FUCA o esa clase de links, va a compartir un Open Graph genérico de fuca que apunte al home.
3. No sé si esta hecho o no pero........ : generar los open graph de una novedad y evento.
4. Falta poner el "Desarrollo por Benteveo". Que sea con Benteveo.com porfa

**Comment by mkreyness** [comment]
no obviamente no esta hecho, vi que en algunos lados lo dejaste dentro del template y en otros usa el include de opengraph generico.
Habria que definir que poner en cada caso que no sea el generico (y llenar con algo el generico)

**Comment by LeandroBraier** [comment]
1- Uds diganme nomás donde cargo cada info y yo la cargo. 

O prefieren que se las de y uds la cargan?

Si es así, diganme los caracteres y se los paso.

De entrada, les digo que como base de la metadescription sería esto:

**La Fundación Cáncer – FUCA (Fundación para la Investigación, Docencia y Prevención del Cáncer), es una organización de la sociedad civil creada en 1983 por los Dres. Reinlado Chacón y José Mordoh, inscripta en la I.G.J. con el N° 33.**

2. Los open graph los ponés vos Fede no?

**Comment by mkreyness** [comment]
yo entiendo que en las novedades y eventos habria que poner o el titulo o la info de bajada (otra cosa automaticamente no podemos extraer).  Pero no se bien en que tags habria que poner cada cosa. Si vas a tocar @FAAREIA podes ponerle directamente los `<!--des-->` o `<!--txt_baj-->` que veas en cada template (siempre que los metatags esten fisicamente dentro del mismo template, no aplica a lo que viene por includes ya que eso es igual para todos)

**Comment by FAAREIA** [comment]
Estuve tocando pero por lo responsivo. Mañana le meto a esto que dicen, una vez que termine el index que me falta algo.
@LeandroBraier la meta description tendría que ser para cada página, las del CMS es otra tema. Yo a lo que me pasaste, le sacaría lo último de "inscripta en la I.G.J. con el N° 33" ya que a nadie que los busque le va a interesar ese dato y tampoco se si va a entrar todo en los resultados de búsqueda.

**Comment by LeandroBraier** [comment]
Perfecto. Dejale esa metadescription para la página principal y de las
demás tomá el primer párrafo. En todos los casos aplica. En el caso de las
notas, eventos y demás lo mismo o la bajada. Lo que te parezca mejor.

abrazo

2016-09-28 15:20 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya estan listas en responsivo:
Contacto, Home, Todas las subsecciones de quienes somos.
Al home les agregué el meta description también.

**Comment by LeandroBraier** [comment]
Genial Fede!! Muchas gracias!! Seguime teniendo al tanto porfa. Fijate que
te pedí recién un ajuastecito en un texto de la landing de Colocador
Klaukol. Si se llega para hoy genial.

**Comment by FAAREIA** [comment]
Ahi subí lo responsivo de todas las subsecciones de Investigación. Mañana sigo con pevención que ya la tengo algo avanzada y hago eso de la foto de parex.

**Comment by LeandroBraier** [comment]
Genial! Gracias! Viste los detallecitos que te pasé aparte?

**Comment by FAAREIA** [comment]
Ya esta listo todo prevención y docencia. Falta menosssss

**Comment by LeandroBraier** [comment]
Vamos todavia Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA nos falta poner el "Desarrollo por Benteveo". Que sea con Benteveo.com porfa

**Comment by FAAREIA** [comment]
Ok, ahi ya subí una nueva actualización. Falta la página del evento hacer responsiva y después revisar que no haya quedado nada pendiente. Luego los open graph y lo que falte.

**Comment by LeandroBraier** [comment]
Vamos todavia que falta menos Fede!!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2016-10-06 18:26 GMT-03:00 Federico Arena <notifications@github.com>:

**Comment by FAAREIA** [comment]
Ya revisé el sitio y esta todo responsivo. @mkreyness te digo algunas cosas que encontré:
- No se renderiza el bloque de facebook ni el del último evento en páginas como Eventos y Novedades.
- En el evento, si no hay slideshow no tiene qe renderizarse su html porque ocupa espacio y tira el texto hacia abajo. Parece que hay uno o 2 enters invisibles.
- El link de Presa -> Novedades lo sacamos? @LeandroBraier

**Comment by mkreyness** [comment]
Facebook / evento: estaban en la maqueta ? Capaz los agregaste despues de que las converti a template.
Slideshow vacio: bueno, tengo que prever entonces que pueda estar vacio y eliminar toda la seccion.

**Comment by FAAREIA** [comment]
Yo pensé que la variable no estaba puesta, pero me fijé y estan. Es raro

**Comment by mkreyness** [comment]
El programa no debe estar reemplazandolas. Ok, en un rato lo arreglo.

**Comment by mkreyness** [comment]
ahi agregue facebook,  porque estaba en los templates y no en el programa, pero lo del ultimo evento ni siquiera esta en los templates. En el caso de eventos me parece que tampoco tendria mucho sentido.
Decime en que orden corresponde agregarlo, entre "Dona" y "Facebook" ?

**Comment by FAAREIA** [comment]
Lo del último evento solo tiene que ir en Novedades. El orden en que estaban era el correcto

**Comment by mkreyness** [comment]
Ahh, es que esta mal escrito, dice "aside-evento" y en todos lados puse "aside-eventos", ya se que va uno solo pero por si despues crecia lo habia dejado asi. Ahora lo corrijo y sale andando.
Quedaria lo del slideshow.

**Comment by FAAREIA** [comment]
### Open Graph

@mkreyness 
Fijate que en campanaT, eventoT y novedadT agregué unas variables que no existian:
-  . URL absoluta del link
-  Tendría que ser un crop sin tags html, de 220 caracteres aprox y que termine en "...". Osea, sería una bajada breve.
-  Es la URL de la primer imágen del slideshow. En el caso del que no hay slideshow, la imagen de apertura del evento o si es una novedad, pone el default de `http://www.fuca.org.ar/img/facebook-og.jpg`

**Comment by mkreyness** [comment]
ah, esto ya es otro precio.
@LeandroBraier recorto yo las descripciones que haya en campañas, eventos y novedades automaticamente a 220 caracteres o queres tener un campo separado para editarlos ?

**Comment by FAAREIA** [comment]
Perdón, el texto que esta como bajada en las categorías sirve perfectamente para la variable `<!--txt_html_fb-->`. Asi que no hagas nada nuevo mejor.
Acordate que esa variable no va en la categoría sino en el artículo en si

**Comment by mkreyness** [comment]
entonces cambialo por  y deberia andar automaticamente a partir de la proxima regeneracion.

**Comment by mkreyness** [comment]
ya esta lo de que se destruya el slideshow si no tiene elementos. Lo hice directamente por javascript al cargar, asi no tenia que complicar la logica del template teniendo dos estructuras anidadas.

**Comment by FAAREIA** [comment]
Creo que ya esta todo hecho. Enumero lo hecho.
- Responsividad del sitio
- Meta descripción y title de todas las páginas
- Open graph general y propio de páginas como la de un evento
- El desarrollado por BTV

Sigo con lo de siguit y después el responsive de revear

**Comment by mkreyness** [comment]
yo con lo del opengraph no toque nada todavia, te alcanzo con usar las variables que ya existian ?

**Comment by FAAREIA** [comment]
No, faltaría la variable , que es el link absoluto y la variable complicada de

**Comment by LeandroBraier** [comment]
Excelente @FAAREIA ! Muchisimas gracias!

Fijate que en el description que aparece al linkear la web en Facebook está mal escrito el nombre del doctor principal. Debería decir:

"La Fundación Cáncer- FUCA, es una organización de la Sociedad Civil creada en 1983 y presidida por los Doctores Reinaldo Chacón y José Mordoh. "

abrazo

**Comment by mkreyness** [comment]
listo lo de link y img_1 en campanas, eventos y novedades. Si ven alguna mal avisenme, no encontre campanas o novedades sin slides como para probar que traiga la imagen default.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! 

Ya está todo entonces? Testeamos en Mobile?

**Comment by FAAREIA** [comment]
Si esta todo hecho, ahora en un rato me fijo el android pero dudo que haya algo para corregir

**Comment by LeandroBraier** [comment]
@FAAREIA querido, me pidieron un agregadito de texto más muy simple. Para mañana (hoy la web está caida pero la están levantando)

Necesito que agregues 2 teléfonos a la sección de contacto, en la parte de oficina

+54-11 2088-3689
+54-11 3221-8900 (interno: 1021)

abrazo

**Comment by FAAREIA** [comment]
Job done

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Lo podrás agregar en el footer también? Ahí también hay 1 tel de oficina y estaría bueno que estén los 3.

**Comment by FAAREIA** [comment]
Ahi esta listo

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA !
