### ISSUE TITLE
Acceso de Cliente a CMS FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#22]
@mkreyness necesito un acceso de cliente al CMS que no pueda borrar cosas. Me lo pasás cuando puedas?

abrazo

**Comment by mkreyness** [comment]
fuca
fuca

Puse que nadie pueda borrar nada, si quieren anular algo se lo pasa a estado "ANULADO" (o "SUSPENDIDO") y listo.

**Comment by LeandroBraier** [comment]
Ok, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! abrazo
