### ISSUE TITLE
URGENTE Redireccionamiento Cuidate a tiempo.org

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#23]
@mkreyness we have a problem: MS dejó vencer el dominio de Cuidateatiempo.org

http://cuidateatiempo.org/

Necesito redireccionarlo urgente desde fuca.org Qué tenemos que hacer? Decime y le aviso al que maneja el dominio y demás.

**Comment by mkreyness** [comment]
recien veo esto, queres hacer algo tipo 
1) hay que preguntar en Duplika cual es el IP actual del servidor de la cuenta "cuidatea", no tengo forma de saberlo porque tampoco puedo entrar al CPanel sin saber ese IP (y via el dominio no anda obviamente).
2) Yo diria que los que tengan delegado el manejo de fuca.org.ar agreguen un A RECORD de un subdomain cuidateatiempo.fuca.org.ar (el cual habra que actualizar cada vez que Duplika cambie de IP) apuntado a ese IP.
3) Una vez funcionando eso, tocamos la pagina para que el link lleve a cuidateatiempo.fuca.org.ar, pero igual capaz muchas cosas ya no esten funcionando bien, como el envio de mails automaticos (si se mandan desde un dominio caido, es muy probable que vayan a spam).

Renovarlo no es una opcion ? No creo que lo hayan comprado todavia.

**Comment by mkreyness** [comment]
verificado: vencio ayer, hay POR LO MENOS 30 dias durante los cuales se puede renovar, me parece que es la opcion mas simple y sencilla.

**Comment by LeandroBraier** [comment]
Dejame que averigue.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
HEcho por MS! Me avisás cuando veas que está todo en orden?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-09-28 18:17 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
veo todo en orden, ya sea entrando por www.cuidateatiempo.org como por el link desde fuca.org.ar

**Comment by LeandroBraier** [comment]
Perfecto MK!! Gracias!!!
