### ISSUE TITLE
Detalles a corregir Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#24]
@FAAREIA te paso 5 observaciones que me pide el cliente:

```
• STAFF  (En FUCA junto a nosotras, colocar a: COORDINADORA DE VOLUNTARIOS Marta Somma)

• http://www.fuca.org.ar/docencia/becarios-exbecarios.php
```

Sacar de PRIMER AÑO a la Dra. Lucía Fuente y colocarla en FELLOWSHIP EN HEMATOLOGÍA  junto a  la Dra. María Azul Cuba.
El año de Azul es sólo 2016 y para Lucía sí va 2016 – 2017

```
• La presentación del stand del  cio está desordenada.  Nosotros la mandamos diferente. El subdirector después del director,  luego los investigadores,  becario postcoc y tesistas.  Despues secretarias y maestranza.  Esta todo mezclado.  Pueden corregirlo 

• Logo de Fleming linkeando la web en la home, chiquito arriba:
```

![logo-alexander-fleming-en-alta](https://cloud.githubusercontent.com/assets/6719872/19046996/5ee8166a-8976-11e6-9dd3-7eabc9e03b61.png)

http://www.alexanderfleming.org/View/1/espanol.aspx

```
• El calendario está mal, decía viernes primero de octubre y es sábado
```

**Comment by FAAREIA** [comment]
- Staff, hecho
- becarios exbecarios, hecho
- Eso de la presentación del stand del cio, no se que link es. Me parece raro que lo haya desordenado, yo suelo copiar y pegar. Más allá de eso como me pareció que el sitio ya estaba revisado y aprobado al 100%, el documento lo borré, lo tenes por ahi asi lo chequeo?
- Lo del fleming lo voy a poner en el footer, arriba traté de colocarlo y como que queda descolgado. Ahi estaría siempre presente.
- Lo del calendario lo tendría que ver @mkreyness pero el detalle de lo que manda es semi-nulo, dónde estaba y qué hizo para que le aparezca el bug ese?

**Comment by FAAREIA** [comment]
Actualizo:
- Staff: Hecho
- Presentación CIO: Hecho (fijarse si esta bien ahora)
- Logo Fleming: Hecho, puesto en el footer. En el header no quedaba
- Calendario: Ver MK

**Comment by LeandroBraier** [comment]
Gracias Fede!! Yo tampoco encuentro el problema la verdad. Consulto con el cliente y les digo.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness ya encontré el bug. Es el calendario de novedades. Mirá:

http://www.fuca.org.ar/novedades/-issueyfucaderosa.html

Dice viernes 1 de octubre y era sábado el 1.

**Comment by mkreyness** [comment]
Upa, y esto viene copiado de Klaukol, donde andan bien. Debe ser que este servidor tiene el default de dias de semana distinto, ahora lo corrijo y regenero.

**Comment by mkreyness** [comment]
listo. Aca parece que el dia 1 de la semana es Martes,  (el lunes es 0) cuando en Duplika (y en la mayoria del universo) en general el dia 1 de la semana es Lunes (y el domingo es 0).

**Comment by LeandroBraier** [comment]
Perfecto. Gracias MK!!! abrazo
