### ISSUE TITLE
Ajustecitos de Texto en Web FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#25]
@FAAREIA me pidieron un ajuste de 1 letra.

En la sección de autoridades, donde dice "Sra María Alejandra Calvo" debe decir "Dra María Alejandra Calvo.

Solo eso.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
