### ISSUE TITLE
Ajustes en Cuidate a tiempo.org

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#26]
@FAAREIA el cliente me pide unos cambios muy puntuales. Me confirmás si llegás el viernes?

1- Sumar un embed del video de Maru Botana: https://vimeo.com/110461977 (lo pondría en la columna izquierda sobre la Trivia.

2- Sacar el logo de Alto Palermo y colocar el de la SAM (va aquí:

![logo-sam](https://cloud.githubusercontent.com/assets/6719872/20301112/ce986748-ab00-11e6-82dc-13820a01f92f.png)

3- Linkear en la parte de "Más info" el mapa de la SAM, bajo el nombre de "Mapa Argentino de Mastología" 

Es una plataforma en la que se puede encontrar información fiable acerca de las instituciones que tratan con patologías mamarias a nivel nacional: http://www.samas.org.ar/archivos/mapa/mapamam.html

abrazo

**Comment by FAAREIA** [comment]
Qué haces Lea, lo hice hoy porque estaba offline todo el servidor de Sadia y Siguit.
http://cuidateatiempo.org/
Fijate si esta ok
Abrazooo

**Comment by LeandroBraier** [comment]
Está perfecto Fede! Le aviso al cliente.

**Comment by LeandroBraier** [comment]
@FAAREIA el cliente pidió cambiar el botón "Mapa Argentino de Mastología" por "Mapa argentino de instituciones que tratan con patologías mamarias". Si podés hacelo aparte, como un botón aparte más grande y ancho.

abrazo

**Comment by FAAREIA** [comment]
Job done

**Comment by LeandroBraier** [comment]
Muchas gracias!
