### ISSUE TITLE
Página Seteo Programador

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#3]
Fede, necesitaría que me diseñes una página más, que sería el seteo del programador (al estilo el del Asistente Dánica). Es una página muy simple a la que llegaría la gente al hacer clic en el mail de bienvenida por si quiere cambiar algún seteo.

**Comment by mkreyness** [comment]
Pero HAY seteos ?
En el form no vi que se pueda elegir dia de semana, ni hora, ni nada.
Para mi lo logico seria que la gente entre a cargar su nueva fecha de 
ultima mamografia, pero eso no lo llamaria un "seteo".
Lo cual me lleva a la siguiente duda: si nadie entra a modificar nada, y 
ya le mande un mail, asumo que por un año no tengo que volverle a 
mandar, aunque no tenga idea de que hizo ?

**Comment by FAAREIA** [comment]
en que quedó esto ?
No me parece mal que haya un form aparte con 1 campo solo, actualizable, diciendo la última vez que hizo la mamografía.
Si nadie modifica nada, es cada un año tengo entendido, luego del primer mail diciendole "esta es tu proxima fecha" o diciendo "hacete una mamografía ya porque hace-mucho/nunca la hiciste"

**Comment by LeandroBraier** [comment]
Estoy repasando el tema. La pregunta mia para MK es: ¿la única forma de
modificar la fecha de la mamografía es a través del link que le llega a la
persona en el mail de bienvenida?

Por ejemplo, si vuelve a la página y vuelve a escribir el mismo mail, ¿no
le aparecerían automáticamente los datos almacenados? Si fuera así no
necesitamos esta página de seteos. Al menos por ahora no.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-16 8:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
```
No solo con el de bienvenida, con cada aviso de que se tiene que
hacer la mamografia.
Es la misma historia que con el asistente Danica.
Que pueda entrar SIN un link autorizado implicaria tener un login, y
un login implicaria una contraseña, si no cualquiera que sepa su
email puede entrar y modificarle los datos.

El 16/10/2014 a las 9:46, LeandroBraier
  escribió:

Estoy repasando el tema. La pregunta mia para MK es:
  ¿la única forma de

  modificar la fecha de la mamografía es a través del link que le
  llega a la

  persona en el mail de bienvenida?


  Por ejemplo, si vuelve a la página y vuelve a escribir el mismo
  mail, ¿no

  le aparecerían automáticamente los datos almacenados? Si fuera así
  no

  necesitamos esta página de seteos. Al menos por ahora no.


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-10-16 8:50 GMT-03:00 Federico Arena
  <notifications@github.com>:


  > en que quedó esto ?

  > No me parece mal que haya un form aparte con 1 campo solo,
  actualizable,

  > diciendo la última vez que hizo la mamografía.

  > Si nadie modifica nada, es cada un año tengo entendido, luego
  del primer

  > mail diciendole "esta es tu proxima fecha" o diciendo "hacete
  una

  > mamografía ya porque hace-mucho/nunca la hiciste"

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/FUCA/issues/3#issuecomment-59349820.
      >
      —
        Reply to this email directly or view
          it on GitHub.
      {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/FUCA/issues/3#issuecomment-59355408">"https://github.com/LeandroBraier/FUCA/issues/3#issuecomment-59355408"</a>,"name":"View Issue"}}

**Comment by LeandroBraier** [comment]
Perfecto. Entonces no necesitamos una página de seteo, lo hacemos exactamente igual que con el asistente dánica, solo que este micrositio tiene todo en esa misma página. Olvidemonos de este ticket por ahora entonces. Lo cierro.

**Comment by mkreyness** [comment]
```
Para cuando nos volvamos a acordar, entonces la idea seria usar el
MISMO form, que le permita actualizar los datos.
Si alguien ingresara manualmente a la pagina y volviera a escribir
sus datos le mostrariamos algun cartel que dijera que ya esta
registrado y use el link del ultimo mail que recibio ?

El 16/10/2014 a las 9:55, LeandroBraier
  escribió:


  Perfecto. Entonces no necesitamos una página de seteo, lo
    hacemos exactamente igual que con el asistente dánica, solo que
    este micrositio tiene todo en esa misma página. Olvidemonos de
    este ticket por ahora entonces. Lo cierro.
  —
    Reply to this email directly or view
      it on GitHub.
  {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/FUCA/issues/3#issuecomment-59356343">"https://github.com/LeandroBraier/FUCA/issues/3#issuecomment-59356343"</a>,"name":"View Issue"}}
```
