### ISSUE TITLE
Mails automáticos FUCA

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#4]
Te paso el texto que debería ir en el mail. 

ESTÉTICA

Estéticamente tomá:
1. El header de la landing (Cuidate a tiempo + logo fuca)
2. El footer de la landing (Más info en FUCA.ORG.AR + 3 logos de instituciones + Desarrollado por Benteveo
3. El texto podés tomar la foto, el color de fondo y las tipografías de "El cáncer tiene cura. Con una mamografía anual es posible cuidarse a tiempo."

TEXTO:

1- En el mail de bienvenida diría a las mujeres mayores de 40 años:

"¡Gracias por programar tu mamografía anual! 

A partir de los 40 años es importante hacer un estudio de este tipo por año para controlar y detectar la aparición de signos de cáncer de mama a tiempo para hacer un tratamiento efectivo.

Recibirás un correo electrónico recordándote que tenés que hacer el estudio en los días previos a la fecha correspondiente. Cuidate a tiempo.

Para modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

2- En el mail de bienvenida diría a las mujeres menores de 20 años:

"¡Gracias por utilizar el programador de mamografías! 

A partir de los 40 años es importante hacer un estudio de este tipo por año para controlar y detectar la aparición de signos de cáncer de mama a tiempo para hacer un tratamiento efectivo. Hasta los 20 años, con los controles ginecológicos habituales es suficiente. 

En los días previos a la fecha en que tengas que empezar a hacer tu mamografías recibirás un correo electrónico recordándote que debés hacer el estudio. Cuidate a tiempo.

Para modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

3- En el mail de recordatorio de que "muy pronto" debe hacerse una mamografía:

"Hola __________ (nombre del usuario)! 

Una vez al año llega la Primavera. Una vez al año te vas de vacaciones. Una vez al año... te hacés una mamografía. 

Te escribimos para recordarte que en tres días se cumple un año desde tu última mamografía. El día _________ (fecha correspondiente) recibirás un nuevo correo electrónico recordándote que debés hacer el estudio. No olvides sacar turno.

A partir de los 40 años hacer un estudio de este tipo por año permite controlar y detectar la aparición de signos de cáncer de mama a tiempo para hacer un tratamiento efectivo. Cuidate a tiempo.

Para modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

4- En el mail de recordatorio efectivo de que debe hacerse una mamografía:

"Hola __________ (nombre del usuario)! 

Te escribimos simplemente para recordarte hoy se cumple un año desde tu última mamografía. No olvides sacar turno para realizarte este importante estudio.

A partir de los 40 años hacer un estudio de este tipo por año permite controlar y detectar la aparición de signos de cáncer de mama a tiempo para hacer un tratamiento efectivo. Cuidate a tiempo.

Para modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

5- Mail de modificación de datos

Gracias por ajustar los datos del programador. Así podemos ayudarte mejor a que te cuides a tiempo.

Para volver a modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

6- Mail de Bienvenida para mujeres de entre 20 y 40 años

¡Gracias por programar tu mamografía! 

A partir de los 40 años es importante hacer un estudio de este tipo por año para controlar y detectar la aparición de signos de cáncer de mama a tiempo para hacer un tratamiento efectivo. Entre los 20 y los 40 años, con una mamografía cada 3 años y los controles ginecológicos habituales es suficiente. 

En los días previos a la fecha en que tengas que hacer tu próxima mamografía recibirás un correo electrónico recordándote que debés hacer el estudio. Cuidate a tiempo.

Para modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

**Comment by FAAREIA** [comment]
Ahi va el primero, decime si esta OK

http://cuidateatiempo.org/mailing/bienvenida/bienvenida.html

**Comment by LeandroBraier** [comment]
Perfecto. El link de modificación de datos va a estar activo cuando lo enviemos efectivamente, no?

En ese caso solo te falta hacer funcional el link de "Más info en FUCA.org.ar" El resto joya. Avancemos con los 5 textos y empecemos a testear.

**Comment by FAAREIA** [comment]
Dale, me olvidé de ese link.
El link de modificación lo genera marce.

**Comment by FAAREIA** [comment]
http://cuidateatiempo.org/mailing/bienvenida-mayores-40.html
http://cuidateatiempo.org/mailing/bienvenida-menores-40.html
http://cuidateatiempo.org/mailing/mamografia-fecha-modificada.html
http://cuidateatiempo.org/mailing/mamografia-muy-pronto.html
http://cuidateatiempo.org/mailing/mamografia-recordatorio.html

El texto del mailing de la fecha actualizada, lo cambié un poco, me parece que el original era muy técnico. Fijate que te parece y sino le pongo el original

Abrazo

**Comment by LeandroBraier** [comment]
QUEDÓ MUY BIEN! Tu texto también, es mejor, es cierto.

Pequeños detalles y ya se lo pasamos a MK:

http://cuidateatiempo.org/mailing/bienvenida-mayores-40.html

Quitar las palabras "controlar y"

<goog_1927556158>
http://cuidateatiempo.org/mailing/bienvenida-menores-40.html

Quitar las palabras "controlar y"

En el recuadro rosa sobra una "S" en la palabra mamografía

http://cuidateatiempo.org/mailing/mamografia-muy-pronto.html

Quitar las palabras "controlar y"

Quitar las palabras "(fecha correspondiente)"

http://cuidateatiempo.org/mailing/mamografia-recordatorio.html

Quitar las palabras "controlar y"

Falta un "que" en "recordarte que hoy se cumple"

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-17 12:24 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Ya esta listo el envio del mail de bienvenida, tanto para mayores como 
menores.
Probá si queres cargar uno de cada uno asi te llegan los mails (no hay 
problema en repetir el mismo mail, no se esta controlando eso por ahora, 
si queremos controlarlo habria que prever mensajes de error en el 
formulario).
Ademas estoy pensando que tendria que haber un boton para darse de baja, 
no ?

El link a modificar funciona bien, pero el mail de respuesta a la 
modificación todavia no lo modifiqué, sigue el que estaba de antes, 
decime si este te anda bien y avanzo con eso.

**Comment by LeandroBraier** [comment]
Demora en llegar, no? Yo todavía no lo recibí.

Consulta MK. ¿Estamos a tiempo de hacer uno más para las mujeres de entre
20 y 40 años que les llegue cada 3 años?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-17 17:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, no deberia demorar. Debe ser que corrido automatico no encuentra las 
librerias nuevas de envio de mail.
Ahora lo corro a mano para que te llegue y reviso eso.

Si, no hay problema, no hice todavia lo del envio por fecha.

**Comment by LeandroBraier** [comment]
Perfecto, Marce. El mailing lo veo perfecto. Avancemos con los demás y le
voy pidiendo a Fede por otro lado el Mail nº 6 para mujeres de entre 20 y
40 años.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-17 17:39 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, te subo el nº 6 editando el ticket que tiene los otros 5.

**Comment by LeandroBraier** [comment]
Fede, subí el mail nº 6 pero hice modificaciones también en el mail nº 2. Habría que impactar esas modificaciones.

**Comment by FAAREIA** [comment]
http://cuidateatiempo.org/mailing/bienvenida-entre-20-40.html
http://cuidateatiempo.org/mailing/bienvenida-mayores-40.html
http://cuidateatiempo.org/mailing/bienvenida-menores-20.html
http://cuidateatiempo.org/mailing/mamografia-fecha-modificada.html
http://cuidateatiempo.org/mailing/mamografia-muy-pronto.html
http://cuidateatiempo.org/mailing/mamografia-recordatorio.html

**Comment by LeandroBraier** [comment]
Gracias Fede!

http://cuidateatiempo.org/mailing/bienvenida-entre-20-40.html

Perfecto!

http://cuidateatiempo.org/mailing/bienvenida-mayores-40.html

No anda el link

http://cuidateatiempo.org/mailing/bienvenida-menores-20.html

Está perfecto, solo te olvidaste de cambiar la primera línea, que ahora debería decir: "¡Gracias por utilizar el programador de mamografías!"

http://cuidateatiempo.org/mailing/mamografia-fecha-modificada.html
http://cuidateatiempo.org/mailing/mamografia-muy-pronto.html
http://cuidateatiempo.org/mailing/mamografia-recordatorio.html

Perfectos.

**Comment by mkreyness** [comment]
Quedo mal el nombre del archivo real, dice "bienvenida-menores-40.html" 
en vez de "bienvenida-mayores-40.html"
Yo ya hice las adaptaciones para que use el que corresponde segun la 
edad (pero tampoco encuentra el de 40).

**Comment by FAAREIA** [comment]
ahi ya estan bien y actualizados

**Comment by LeandroBraier** [comment]
Fede, te pido agregar un mailing nº 7. 

Este se enviaría un mes después del mailing 4, de recordatorio efectivo. Debería decir lo siguiente:

"¿Ya te hiciste tu mamografía anual, __________ (nombre del usuario)?

Hace un mes se cumplió la fecha de tu mamografía anual. Simplemente te escribimos para pedirte una última colaboración antes de dejar de enviarte recordatorios por once meses.

Por favor, si aún no la hiciste, te recordamos que pidas un turno lo antes posible. En caso de que sí la hayas hecho, ¡excelente! Te pedimos que anotes la fecha de la misma haciendo clic aquí y te recordaremos cuando haya pasado un año.

Gracias por tomar conciencia de lo importante que es cuidarte a tiempo.

Para modificar la fecha de tu última mamografía en el sistema, hacé clic aquí"

abrazo

**Comment by FAAREIA** [comment]
Hecho.
http://cuidateatiempo.org/mailing/mamografia-actualizacion.html

**Comment by LeandroBraier** [comment]
Está perfecto Fede. Solo dos preguntas:

1: El "hacé clic aquí" del párrafo "Por favor, si aún no lo hiciste..." debe ser clickeable. Debe llevar al mismo URL que el link del footer.

2: ¿Ya están responsive todos los mails?

**Comment by FAAREIA** [comment]
1- No entendí creo que esta incompleta la pregunta. Igualmente el link se lo pone Marce.
2- Los mails no pueden ser responsivos, le puse 640px de ancho fijo.

**Comment by LeandroBraier** [comment]
Ahí corregí la parte 1. Respecto de la 2, yo en Android los veo bastante hechos pelota a los mails, si bien se pueden corregir. Tendríamos que mejorar eso. Ahora te paso capturas para que veas a qué me refiero.

**Comment by FAAREIA** [comment]
Ahi arregle lo del link.
Con respecto al 2, espero el screenshot

**Comment by mkreyness** [comment]
Yo mas tarde implemento el envio de esos mails y lo pruebo.

**Comment by LeandroBraier** [comment]
Perfecto, MK. Gracias!

**Comment by mkreyness** [comment]
Necesito que me pases con que asunto se manda este nuevo mail de 
actualizacion.

**Comment by LeandroBraier** [comment]
El asunto es: ¿Ya hiciste tu mamografía anual, NOMBRE APELLIDO?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Todo listo.
Ahora voy a forzar las cosas para que te llegue una, avisame el resultado.

**Comment by LeandroBraier** [comment]
Recibido!

Van 2 cosas para este mail y uno para todos en general.

1) El usuario aparece con el nombre en minúscula. Si es por como lo ingresé yo todo bien. Queda así.

2) La frase "haciendo clic aquí" del párrafo: "Por favor, si aún no lo hiciste" debe tener un link que lleve a la misma URL que "hacé clic aquí" al pie del mail.

MAILS EN GENERAL

3) Qué hacemos si alguien responde al mail fuca@cuidateatiempo.org?? Por las dudas ponele un forward que me llegue a mi a leandro@benteveo.tv

abrazo

**Comment by mkreyness** [comment]
1) si, sale tal cual fue escrito por el usuario.
Podria ponerlo todo en mayuscula, o forzarle la primer letra a mayuscula 
de nombre y de apellido y el resto dejarlo como esté.
Pero por ejemplo si pusiste

maria cristina perez garcia

saldria:

Maria cristina Perez garcia

lo cual tambien esta mal.

2) Ok, no debe estar previsto en el template, si no se hubiera 
reemplazado automaticamente. Ahora me fijo.

3) No hay nada instalado, voy a ver si desde CPanel se puede hacer.

**Comment by mkreyness** [comment]
2) ya lo cambie y ahora te deberia estar llegando de nuevo.

**Comment by LeandroBraier** [comment]
Hecho! Perfecto MK. Automaticemos esta también entonces. Cuando esté hecho
avisame y ya cierro el ticket.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-22 17:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
3) Listo, ya te mande una respuesta a un mail que me llego, confirmame.

Automatizar que cosa decis, el mail ?
Ya esta automatico (no te lo mandé yo en ninguno de los casos, solo 
forcé tus fechas en el CMS para que se dispare solito).

**Comment by LeandroBraier** [comment]
Perfecto entonces! Gracias!
