### ISSUE TITLE
Trivia Cuidate a Tiempo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#5]
Lo ideal es que sea solo un pop up. La pregunta es:

¿Cuál de estos tres no es un factor de riesgo del cáncer de mama
1. Edad avanzada
2. Incidencia sobre sexo
3. Exposición al sol

La respuesta correcta es la 3. 

Respuesta correcta:

¡Felicitaciones! La exposición al sol no es un factor de riesgo del cáncer de mama, sino de otro tipo de tumores. En cambio, el cáncer de mama es 100 veces más común entre las mujeres que entre los hombres y aproximadamente 2 de 3 cánceres invasivos de este tipo se encuentra en personas de 55 años o más.

¡Has aprendido algo nuevo! Tu respuesta es incorrecta. La exposición al sol no es un factor de riesgo del cáncer de mama, sino de otro tipo de tumores. En cambio, el cáncer de mama es 100 veces más común entre las mujeres que entre los hombres y aproximadamente 2 de 3 cánceres invasivos de este tipo se encuentra en personas de 55 años o más.

Cuando tengas esta diseñada vemos si hacemos rotativa cambiando los factores de riesgo dos o tres veces para hacer 3 variantes.

abrazo

**Comment by FAAREIA** [comment]
Ok.
Ahi hice un ajuste para resoluciones grandes.
http://cuidateatiempo.org/

En realidad la versión original debería haber sido la grande, ya que a la chica siempre se le sacan cosas. Partiendo de la versión chica, no tenemos que agregar ahora.

**Comment by FAAREIA** [comment]
Los factores de riesgo van a cambiar de orden siempre o van a cambiar los textos?

**Comment by FAAREIA** [comment]
http://cuidateatiempo.org/?contacto=1   -> Es el mensaje OK, mejorado

La trivia ya esta también

Abrazo

**Comment by mkreyness** [comment]
Actualizaste tambien indexT ?

Enviado desde mi iPhone

**Comment by FAAREIA** [comment]
No, solo el original

**Comment by LeandroBraier** [comment]
Perfecto el mensaje, Fede. La trivia no me funciona, puede ser?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si elegis una opción, tiene que agrandarse la altura del bloque y aparecer el texto.
No lo probe en safari, pero debería funcionar.

**Comment by mkreyness** [comment]
Pero pasa los cambios al otro, si no los que entran por links desde mails no lo ven.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Yo lo estoy probando en Chrome y no me funciona. En Firefox tampoco.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Me había olvidado de subir un archivo.
Lo de indexT.html ya esta también.

**Comment by LeandroBraier** [comment]
Ahora sí, está perfecta la trivia.

Testeemos los mailings así ya nos quedamos tranquilos que está todo listo y
te paso un par de opciones más de la trivia para que no sean siempre las
misma.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Cuando vuelvo a ingresar a la trivia ya respondida no se reseteó. Sigue con la opción que yo marqué. No solo eso. Si toco una segunda opción quedan seleccionadas ambas. Si toco la tercera quedan las tres. Habría que corregir eso.

abrazo

**Comment by FAAREIA** [comment]
Ya esta todo listo

**Comment by LeandroBraier** [comment]
La trivia quedó joya. Terminamos los mailings y subí estas otras dos variantes de la trivia. La pregunta sigue siendo la misma, cambian las opciones:

VERSIÓN 2
1. Factores Genéticos
2. Alimentación
3. Ingerir bebidas alcohólicas

La respuesta correcta es la 2.

Textos:

¡Felicitaciones! No se ha podido comprobar efectivamente que la alimentación con determinados componentes sea un factor de riesgo del cáncer de mama, pero sí la ingestión de bebidas alcohólicas. Respecto de factores genéticos, se estima que 5 de cada 10 casos de cáncer de mama son hereditarios. 

¡Has aprendido algo nuevo! Tu respuesta es incorrecta. No se ha podido comprobar efectivamente que la alimentación con determinados componentes sea un factor de riesgo del cáncer de mama, pero sí la ingestión de bebidas alcohólicas. Respecto de factores genéticos, se estima que 5 de cada 10 casos de cáncer de mama son hereditarios. 

VERSIÓN 3
1. Actividad física
2. Un familiar directo lo padece
3. Antecedentes personales de este tipo de cáncer.

La respuesta correcta es la 1.

Textos:

¡Felicitaciones! Cada vez hay más evidencia científica de que el ejercicio físico, por el contrario, disminuye el riesgo de cáncer de mama. En cambio, lamentablemente, antecentes de cáncer de mama en un familiar directo cosanguíneo o en uno u otro de los propios senos implica mayores posibilidades de contraer esta enfermedad. 

¡Has aprendido algo nuevo! Tu respuesta es incorrecta. Cada vez hay más evidencia científica de que el ejercicio físico, por el contrario, disminuye el riesgo de cáncer de mama. En cambio, lamentablemente, antecedentes de cáncer de mama en un familiar directo cosanguíneo o en uno u otro de los propios senos implica mayores posibilidades de contraer esta enfermedad.

**Comment by FAAREIA** [comment]
Ahi ya esta lo de las trivias.
ctrl F5

**Comment by LeandroBraier** [comment]
Buenísimo quedó! Solo dos cositas:
1. Ojo que en la VERSIÓN 2, cuando respondes correctamente, en el párrafo
   largo dice "antecentes" en lugar de "antecedentes"
2. Sigue permitiendo que respondamos varias casillas al mismo tiempo,
   cuando siempre debería poder seleccionarse una sola.

Lo demás perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
solucionado.
ctrl F5

**Comment by LeandroBraier** [comment]
Genial.

**Comment by LeandroBraier** [comment]
Fede, quedó perfecto. Una sola cosa. Fijate la captura que te adjunto:

Al subir el link de la home del sitio a redes sociales toma como metadescripcion el texto de la trivia. Evitemos esto. Ahora te subo un ticket para la metadata correcta del sitio.

abrazo

![captura de pantalla 2014-10-20 a la s 10 14 59](https://cloud.githubusercontent.com/assets/6719872/4701692/b44fe8e2-585b-11e4-93a0-da1dfab4ea47.png)

**Comment by LeandroBraier** [comment]
Esto sigue igual Fede, apenas puedas corregilo porfa, sino nadie va a poner el link en su muro.

abrazo

**Comment by FAAREIA** [comment]
Fijate de republicarlos, si sigue igual creo que hay que meter otros tags

**Comment by LeandroBraier** [comment]
Sigue igual. No entiendo bien a qué te referís con otros tags, pero después de las prioridades de hoy vemos qué puede estar pasando. Vos ya le pusiste la metadata completa a la página no?

**Comment by FAAREIA** [comment]
Ya le puse unos tags de FB con la data del sitio, fijate si te modificó el actual (lo dudo) y sino probá otra vez

**Comment by LeandroBraier** [comment]
Ya lo resolví, Fede. Parece que Facebook aparece a relevar la info en 1 momento y lo que agarró queda, no vuelve a revisar la web, salvo que lo fuerces. Eso hice y funcionó.

Aquí está la explicación completa, tomala para futuras webs que armemos. 

"FB no visita una página cada vez se comparte. Se guarda la info y si hay cambios, pues no se entera. Si en el momento en el que visita la página recoge mal la info, por lo que sea, ahí se queda guardado y no vuelve a parsearla hasta el cabo de nosecuánto.

Cuando te pase esto puedes forzar a facebook a que vuelva a revisar una página y así actualice los datos que tiene guardados (título, descripción, imagen ...) usando una herramienta muy interesante que tiene (un debugger) que te indica lo que debes corregir en tu código fuente y de paso actualiza la info que tenía guardada.

En el momento en el que pasé tu página por el debugger se actualizó en facebook y ahora ya sale todo correcto. Igual el debugger indica que hay cosas que debes corregir, dale un vistazo"

https://developers.facebook.com/tools/debug/og/object/

abrazo

**Comment by FAAREIA** [comment]
Excelente la data Lea, no sabía!
Me lo guardo cmo bookmark
Abrazo
