### ISSUE TITLE
Metadata Cuidate a tiempo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#8]
Fede, pongamosle la metadata:

Título de la página: Cuidate a tiempo/ Una campaña de FUCA

Descripción: El cáncer de mama tiene cura. Con una mamografía anual a partir de los 40 años es posible detectarlo a tiempo. Programá tu mamografía de una vez para toda la vida en este sitio. "Cuidate a tiempo" es una campaña de la Fundación FUCA para prevenir el cáncer de mama.

metatags: cancer de mama, programar, mamografía, FUCA

**Comment by FAAREIA** [comment]
Ahi le pude esa data, le cambie un poco a esto:

Descripción
El cáncer de mama tiene cura. Con una mamografía anual es posible detectarlo a tiempo. Programá tu mamografía de una vez para toda la vida en este sitio.

Pensá que es hasta 120 o 140 caracteres, hay que ser corto.

En las keyword puse:
Cancer de mama, Mamografía, Mamografía anual, Evitar cancer de mama, FUCA

Le saqué "programar", porque no esta relacionado.

**Comment by LeandroBraier** [comment]
perfecto, Fede. Gracias!
