### ISSUE TITLE
Subir SiteMap Cuidate a Tiempo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/FUCA#9]
Fede, necesito que:
1. Subas las versión CON y SIN "WWW" a Google Analytics.
2. Subas el XML del sitemap que te mando por mail a la root de cuidateatiempo.org 

Cuando la tengas, avisame así subo la url http://www.cuidateatiempo.org/sitemap.xml a la página de Google Webmaster, es decir, a:

https://www.google.com/webmasters/tools/sitemap-list?hl=es&siteUrl=http://cuidateatiempo.org/#MAIN_TAB=1&CARD_TAB=-1

**Comment by FAAREIA** [comment]
Idem issue de rio ancho, pero aca hay solo 1 página. no hace falta un sitemap.
